
const VERSION='7.0.0';
const labels={home:'الرئيسية',incomePage:'الدخل',fixedPage:'المصاريف الثابتة',variablePage:'المصاريف المتغيرة',debtsPage:'الديون والأقساط',goalsPage:'الخزائن والأهداف',calendarPage:'التقويم المالي',reportsPage:'التقارير',advisorPage:'التحليل المالي',settingsPage:'الإعدادات'};
const typeLabels={income:'💰 دخل',expense:'🧾 مصروف',fixed:'📌 التزام ثابت',debt:'💳 دين / قسط',vault:'🏦 تحويل لخزينة',goal:'🎯 هدف جديد'};
const REAL_SEED={
 version:VERSION,offset:0,
 transactions:[
  {id:'sep-salary',type:'income',name:'الراتب',amount:13780,date:'2026-09-27',incomeKind:'salary',recurring:true},
  {id:'sep-wife',type:'fixed_payment',name:'الزوجة',amount:500,date:'2026-09-27'},
  {id:'sep-mobile',type:'fixed_payment',name:'الجوال',amount:650,date:'2026-09-27'},
  {id:'sep-electric',type:'fixed_payment',name:'الكهرباء',amount:323.63,date:'2026-09-27'},
  {id:'sep-uni',type:'fixed_payment',name:'الجامعة',amount:675,date:'2026-09-27'},
  {id:'sep-tabby193',type:'debt_payment',name:'تابي 193',amount:193,date:'2026-09-27'},
  {id:'sep-tabby222',type:'debt_payment',name:'تابي 222',amount:222,date:'2026-09-27'},
  {id:'sep-tickets',type:'debt_payment',name:'تذاكر',amount:282.51,date:'2026-09-27'},
  {id:'sep-tamara152',type:'debt_payment',name:'تمارا 152',amount:158.48,date:'2026-09-27'},
  {id:'sep-tamara450',type:'debt_payment',name:'تمارا 450',amount:450,date:'2026-09-27'},
  {id:'sep-loans',type:'debt_payment',name:'القروض الآلية',amount:3222.24,date:'2026-09-27'},
  {id:'sep-emergency',type:'vault',goalId:'g-emergency',name:'تحويل للطوارئ',amount:1000,date:'2026-09-27'}
 ],
 fixed:[
  {id:'f-house',name:'البيت',amount:1000,startDate:'2026-09-01',dueDay:27},
  {id:'f-kids',name:'العيال',amount:900,startDate:'2026-09-01',dueDay:27},
  {id:'f-wife',name:'الزوجة',amount:500,startDate:'2026-09-01',dueDay:27},
  {id:'f-mobile',name:'الجوال',amount:500,startDate:'2026-10-01',dueDay:27},
  {id:'f-wife-mobile',name:'جوال الزوجة',amount:150,startDate:'2026-09-01',dueDay:27},
  {id:'f-electric',name:'الكهرباء',amount:480,startDate:'2026-09-01',dueDay:27},
  {id:'f-water',name:'الماء',amount:125,startDate:'2026-09-01',dueDay:27},
  {id:'f-uni',name:'الجامعة',amount:725,startDate:'2026-09-01',dueDay:27}
 ],
 debts:[
  {id:'d1',name:'القرض الرئيسي',total:98000,remaining:98000,monthly:2887.24,dueDate:'2026-10-27',installments:36},
  {id:'d2',name:'القرض الثاني',total:5000,remaining:5000,monthly:98,dueDate:'2026-10-27',installments:0},
  {id:'d3',name:'القرض الثالث',total:2880,remaining:2880,monthly:237,dueDate:'2026-10-27',installments:0},
  {id:'dt193',name:'تابي',total:579,remaining:386,monthly:193,dueDate:'2026-10-08',installments:2},
  {id:'dtickets',name:'التذاكر',total:1410,remaining:1127.49,monthly:282.51,dueDate:'2026-10-02',installments:4},
  {id:'dtamara152',name:'تمارا',total:456,remaining:297.52,monthly:158.48,dueDate:'2026-10-13',installments:2},
  {id:'dac',name:'المكيف',total:2700,remaining:2700,monthly:450,dueDate:'2026-10-27',installments:6}
 ],
 goals:[
  {id:'g-emergency',name:'الطوارئ',target:15000,initial:0,targetDate:''},
  {id:'g-house',name:'البيت',target:0,initial:1000,targetDate:''},
  {id:'g-istanbul',name:'السفر',target:12000,initial:0,targetDate:''},
  {id:'g-majlis',name:'المجلس النسائي',target:3500,initial:0,targetDate:''},
  {id:'g-ramadan',name:'رمضان والعيد',target:2000,initial:0,targetDate:''},
  {id:'g-adha',name:'الأضحية',target:2000,initial:0,targetDate:''}
 ],
 settings:{salaryDay:27,hijri:true,notifications:true}
};
const blank=REAL_SEED;
function load(){try{
 const v4=JSON.parse(localStorage.getItem('mali-v4'));
 if(v4) return v4;
 return structuredClone(REAL_SEED);
}catch(e){return structuredClone(REAL_SEED)}}
let state=load(), currentType=null, editRef=null;
const $=id=>document.getElementById(id), fmt=n=>new Intl.NumberFormat('ar-SA-u-nu-latn',{maximumFractionDigits:2}).format(Number(n)||0)+' ر.س';
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function monthDate(){let d=new Date();d.setDate(1);d.setMonth(d.getMonth()+state.offset);return d}
function monthKey(){let d=monthDate();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function currentDate(){return new Date().toISOString().slice(0,10)}
function saveState(msg){localStorage.setItem('mali-v4',JSON.stringify(state));render();if(msg)toast(msg)}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function appliesDate(date){return (date||'').startsWith(monthKey())}
function recurringApplies(x){if(!x.startDate)return true; return monthKey()>=x.startDate.slice(0,7)}
function goalBalance(id){let g=state.goals.find(x=>x.id===id);return (g?.initial||0)+state.transactions.filter(x=>x.type==='vault'&&x.goalId===id).reduce((s,x)=>s+x.amount,0)}
function totals(){
 const tx=state.transactions.filter(x=>appliesDate(x.date));
 const income=tx.filter(x=>x.type==='income').reduce((s,x)=>s+x.amount,0);
 const expenses=tx.filter(x=>['expense','fixed_payment','debt_payment','vault'].includes(x.type)).reduce((s,x)=>s+x.amount,0);
 const debt=state.debts.reduce((s,x)=>s+Math.max(0,x.remaining),0);
 const upcomingFixed=state.fixed.filter(recurringApplies).reduce((s,x)=>s+x.amount,0);
 const upcomingDebt=state.debts.filter(x=>x.monthly>0&&x.remaining>0).reduce((s,x)=>s+Math.min(x.monthly,x.remaining),0);
 return {income,expenses,debt,available:income-expenses,upcomingFixed,upcomingDebt,tx}
}
function buildNav(target){target.innerHTML='';Object.entries(labels).forEach(([id,l],i)=>{let b=document.createElement('button');b.textContent=l;b.className=id==='home'?'active':'';b.onclick=()=>show(id);target.appendChild(b)})}
buildNav($('nav'));buildNav($('mobileNav'));
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.textContent===labels[id]));closeDrawer();scrollTo(0,0)}
function render(){
 const t=totals();$('monthLabel').textContent=new Intl.DateTimeFormat('ar-SA-u-ca-gregory-nu-latn',{month:'long',year:'numeric'}).format(monthDate())+(state.settings.hijri?' · '+new Intl.DateTimeFormat('ar-SA-u-ca-islamic-umalqura-nu-latn',{month:'long',year:'numeric'}).format(monthDate()):'');$('available').textContent=fmt(t.available);$('income').textContent=fmt(t.income);$('spent').textContent=fmt(t.expenses);$('debt').textContent=fmt(t.debt);let upcoming=t.upcomingFixed+t.upcomingDebt;$('upcoming').textContent=fmt(upcoming);$('spentMini').textContent=fmt(t.expenses);$('remainMini').textContent=fmt(t.available);$('spendProgress').style.width=(t.income?Math.min(100,Math.max(0,t.expenses/t.income*100)):0)+'%';let now=new Date(),pay=new Date(now.getFullYear(),now.getMonth(),state.settings.salaryDay);if(pay<now)pay=new Date(now.getFullYear(),now.getMonth()+1,state.settings.salaryDay);$('salaryDays').textContent=Math.max(0,Math.ceil((pay-now)/86400000))+' يوم';
 let ratio=t.income?Math.max(0,t.expenses/t.income):0,s=$('status');
 if(!t.income&&!t.expenses){s.className='status attention';s.textContent='ابدأ التسجيل';$('heroText').textContent='أضف دخلك ومصروفاتك من زر +، وستتحدث الأرقام مباشرة.'}
 else{let cls=ratio<.65?'comfortable':ratio<.85?'attention':'pressure';s.className='status '+cls;s.textContent=ratio<.65?'مريح':ratio<.85?'انتبه':'ضغط';$('heroText').textContent=`المصروفات المسجلة تمثل ${Math.round(ratio*100)}٪ من الدخل المسجل لهذا الشهر.`}
 $('alertBox').textContent=!t.income?'سجل الدخل أولًا حتى أقدر أحسب المتاح والهامش بدقة.':t.available<0?`المصروفات والمدفوعات تجاوزت الدخل بـ ${fmt(Math.abs(t.available))}.`:`المتاح الحالي ${fmt(t.available)}. الالتزامات الشهرية المعرفة في النظام ${fmt(upcoming)} قبل احتساب ما تم دفعه منها.`;
 $('goals').innerHTML=state.goals.length?state.goals.map(g=>{let b=goalBalance(g.id),p=g.target?Math.min(100,Math.round(b/g.target*100)):0;return `<div class="goal"><strong>${esc(g.name)}</strong><div class="progress"><i style="width:${p}%"></i></div><small>${fmt(b)} من ${fmt(g.target)} • ${p}%</small></div>`}).join(''):'<div class="empty">ما عندك أهداف حتى الآن. أضف هدف أو خزينة من زر +.</div>';
 let commitments=[...state.fixed.filter(recurringApplies).map(x=>({name:x.name,amount:x.amount,date:'يوم '+(x.dueDay||'—'),kind:'مصروف ثابت'})),...state.debts.filter(x=>x.remaining>0&&x.monthly>0).map(x=>({name:x.name,amount:Math.min(x.monthly,x.remaining),date:x.dueDate||'—',kind:'قسط'}))].slice(0,6);$('recent').innerHTML=commitments.length?commitments.map(x=>`<div class="row"><div><strong>${esc(x.name)}</strong><br><small>${esc(x.date)}</small></div><div class="amt">${fmt(x.amount)}</div><span class="pill">${x.kind}</span></div>`).join(''):'<div class="empty">لا توجد التزامات قادمة.</div>';
 renderPages()
}
function actionButtons(kind,id){return `<span class="fixedActions"><button class="mini primaryMini" onclick="editItem('${kind}','${id}')">✎ تعديل</button><button class="mini danger" onclick="deleteItem('${kind}','${id}')">⌫ حذف</button></span>`}
function renderPages(){
 const txIncome=state.transactions.filter(x=>x.type==='income'&&appliesDate(x.date)),txExpense=state.transactions.filter(x=>x.type==='expense'&&appliesDate(x.date));
 $('incomePage').innerHTML=pageList('الدخل',txIncome,'income',x=>`${fmt(x.amount)} • ${esc(x.date)}`);
 $('variablePage').innerHTML=pageList('المصاريف المتغيرة',txExpense,'expense',x=>`${fmt(x.amount)} • ${esc(x.date)}`);
 $('fixedPage').innerHTML=`<div class="sectionhead"><h3>المصاريف الثابتة</h3><button class="link" onclick="chooseType('fixed')">+ إضافة</button></div><div class="list">${state.fixed.map(x=>{let actual=fixedActual(x.id),pct=x.amount?actual/x.amount*100:0,diff=actual-x.amount,cls=actual===0?'neutral':diff<=0?'good':'bad',txt=actual===0?'لم يسجل الفعلي بعد':diff===0?'مطابق للمخطط':diff<0?`أقل ${Math.abs(diff).toLocaleString('en-US')} ر.س (${Math.abs(100-pct).toFixed(0)}%)`:`زيادة ${diff.toLocaleString('en-US')} ر.س (${pct.toFixed(0)}% من المخطط)`;return `<div class="fixedItem"><div class="fixedTop"><div><strong>${esc(x.name)}</strong><br><small>يبدأ ${esc(x.startDate)} • الاستحقاق يوم ${esc(x.dueDay||'—')}</small></div><div class="fixedActions"><button class="mini primaryMini" onclick="editItem('fixed','${x.id}')">✎ تعديل</button><button class="mini payMini" onclick="payFixed('${x.id}')">✓ تسجيل الفعلي</button><button class="mini danger" onclick="deleteItem('fixed','${x.id}')">⌫ حذف</button></div></div><div class="fixedStats"><div class="fixedStat"><small>المخطط</small><b>${fmt(x.amount)}</b></div><div class="fixedStat"><small>الفعلي</small><b>${state.transactions.some(t=>appliesDate(t.date)&&matchedFixed(t,x))?fmt(actual):'—'}</b></div><div class="fixedStat variance ${cls}"><small>النتيجة</small><b>${txt}</b></div></div></div>`}).join('')||'<div class="empty">لا توجد مصاريف ثابتة.</div>'}</div>`;
 $('debtsPage').innerHTML=`<div class="sectionhead"><h3>الديون والأقساط</h3><button class="link" onclick="chooseType('debt')">+ إضافة</button></div><div class="list">${state.debts.map(x=>`<div class="row"><div><strong>${esc(x.name)}</strong><br><small>المتبقي ${fmt(x.remaining)} • القسط ${fmt(x.monthly)} • الاستحقاق ${esc(x.dueDate||'—')}</small></div>${actionButtons('debt',x.id)}<button class="mini" onclick="payDebt('${x.id}')">دفع قسط</button></div>`).join('')||'<div class="empty">لا توجد ديون.</div>'}</div>`;
 $('goalsPage').innerHTML=`<div class="sectionhead"><h3>الخزائن والأهداف</h3><button class="link" onclick="chooseType('goal')">+ هدف</button></div><div class="list">${state.goals.map(x=>`<div class="row"><div><strong>${esc(x.name)}</strong><br><small>${fmt(goalBalance(x.id))} من ${fmt(x.target)} • ${esc(x.targetDate||'بدون تاريخ')}</small></div>${actionButtons('goal',x.id)}<button class="mini" onclick="chooseType('vault','${x.id}')">تحويل</button></div>`).join('')||'<div class="empty">لا توجد أهداف.</div>'}</div>`;
 renderCalendar();let t=totals();
 $('reportsPage').innerHTML=`<div class="sectionhead"><h3>تقرير الشهر</h3></div><div class="grid"><div class="card"><div class="label">الدخل</div><div class="value">${fmt(t.income)}</div></div><div class="card"><div class="label">الخارج</div><div class="value">${fmt(t.expenses)}</div></div><div class="card"><div class="label">صافي الحركات</div><div class="value">${fmt(t.available)}</div></div><div class="card"><div class="label">الدين المتبقي</div><div class="value">${fmt(t.debt)}</div></div></div>`;
 $('advisorPage').innerHTML=`<div class="card"><h3>التحليل المالي</h3><p>قراءة حسابية للدورة المختارة، مبنية على الحركات والالتزامات المسجلة.</p><button class="primary" style="margin-top:10px;width:100%" onclick="localAdvice()">حلّل وضعي</button><div id="answer" style="margin-top:14px"></div></div>`;
 $('settingsPage').innerHTML=`<div class="sectionhead"><h3>الإعدادات</h3></div><div class="settings"><div class="setting"><span>يوم نزول الراتب</span><input class="btn" type="number" min="1" max="31" value="${state.settings.salaryDay}" onchange="state.settings.salaryDay=+this.value;saveState()"></div><div class="setting"><span>التقويم الهجري</span><input type="checkbox" ${state.settings.hijri?'checked':''} onchange="state.settings.hijri=this.checked;saveState()"></div><div class="setting"><span>إصدار التطبيق</span><b>V${VERSION}</b></div><div class="setting"><span>مكان البيانات</span><b>على هذا الجهاز</b></div></div>`
}
function pageList(title,arr,type,sub){return `<div class="sectionhead"><h3>${title}</h3><button class="link" onclick="chooseType('${type}')">+ إضافة</button></div><div class="list">${arr.map(x=>`<div class="row"><div><strong>${esc(x.name)}</strong><br><small>${sub(x)}</small></div>${actionButtons('transaction',x.id)}<span class="pill">${typeLabels[type]}</span></div>`).join('')||'<div class="empty">لا توجد بيانات.</div>'}</div>`}
function renderCalendar(){let d=monthDate(),y=d.getFullYear(),m=d.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),cells='';for(let i=0;i<first;i++)cells+='<div></div>';for(let n=1;n<=days;n++){let ds=`${y}-${String(m+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`,ev=state.transactions.filter(x=>x.date===ds);cells+=`<div class="day"><b>${n}</b>${state.settings.hijri?`<i class="hj">${new Intl.DateTimeFormat("ar-SA-u-ca-islamic-umalqura-nu-latn",{day:"numeric"}).format(new Date(y,m,n))}</i>`:""}${ev.slice(0,2).map(x=>`<div class="dot">${esc(x.name)}</div>`).join('')}</div>`}$('calendarPage').innerHTML=`<div class="sectionhead"><h3>التقويم المالي</h3><small>ميلادي${state.settings.hijri?' + هجري':''}</small></div><div class="calendar">${cells}</div>`}
const schemas={
 income:[['name','اسم الدخل','text'],['amount','المبلغ','number'],['date','التاريخ','date'],['incomeKind','النوع','select','راتب|salary,دخل إضافي|extra'],['recurring','يتكرر شهريًا','checkbox']],
 expense:[['name','اسم المصروف','text'],['amount','المبلغ','number'],['date','التاريخ','date'],['notes','ملاحظات','text']],
 fixed:[['name','اسم المصروف الثابت','text'],['amount','المبلغ الشهري','number'],['startDate','يبدأ من','date'],['dueDay','يوم الاستحقاق','number']],
 debt:[['name','اسم الدين / القسط','text'],['total','إجمالي الدين','number'],['remaining','المتبقي','number'],['monthly','القسط الشهري','number'],['dueDate','تاريخ الاستحقاق القادم','date'],['installments','عدد الأقساط المتبقية','number']],
 goal:[['name','اسم الهدف / الخزينة','text'],['target','المبلغ المستهدف','number'],['initial','رصيد البداية قبل التحويلات المسجلة','number'],['targetDate','التاريخ المستهدف','date']],
 vault:[['goalId','الخزينة','goalSelect'],['amount','مبلغ التحويل','number'],['date','التاريخ','date'],['name','وصف التحويل','text']]
};
function fieldHTML(f,val=''){let [id,label,type,opts]=f;if(type==='select')return `<div class="field"><label>${label}</label><select id="f_${id}">${opts.split(',').map(o=>{let [a,b]=o.split('|');return `<option value="${b}" ${val===b?'selected':''}>${a}</option>`}).join('')}</select></div>`;if(type==='goalSelect')return `<div class="field"><label>${label}</label><select id="f_${id}">${state.goals.map(g=>`<option value="${g.id}" ${val===g.id?'selected':''}>${esc(g.name)}</option>`).join('')}</select></div>`;if(type==='checkbox')return `<div class="field"><label>${label}</label><input id="f_${id}" type="checkbox" ${val?'checked':''}></div>`;return `<div class="field"><label>${label}</label><input id="f_${id}" type="${type}" value="${esc(val)}" ${type==='number'?'min="0" step="any" inputmode="decimal"':''}></div>`}
function openTypes(){$('typeOverlay').classList.add('show')}
function chooseType(t,presetGoal=''){closeAll();currentType=t;editRef=null;if(t==='vault'&&!state.goals.length){toast('أنشئ هدف أو خزينة أولًا');return}$('formTitle').textContent=typeLabels[t];$('formFields').innerHTML=schemas[t].map(f=>fieldHTML(f,(f[0]==='date'||f[0]==='startDate')?currentDate():(f[0]==='goalId'?presetGoal:''))).join('');$('formOverlay').classList.add('show')}
function closeAll(){$('typeOverlay').classList.remove('show');$('formOverlay').classList.remove('show')}
function readForm(){let o={};for(const f of schemas[currentType]){let el=$('f_'+f[0]);o[f[0]]=f[2]==='checkbox'?el.checked:(f[2]==='number'?Number(el.value||0):el.value.trim())}return o}
function validate(o){if(currentType!=='vault'&&!o.name)return 'اكتب الاسم';if(['income','expense','fixed','vault'].includes(currentType)&&!(o.amount>0))return 'أدخل مبلغ أكبر من صفر';if(currentType==='debt'&&!(o.total>0||o.remaining>0))return 'أدخل قيمة الدين';if(currentType==='goal'&&!(o.target>0))return 'أدخل المبلغ المستهدف';return ''}
$('saveBtn').onclick=()=>{let o=readForm(),err=validate(o);if(err){toast(err);return}
 if(editRef){let arr=editRef.kind==='transaction'?state.transactions:arrOf(editRef.kind);let i=arr.findIndex(x=>x.id===editRef.id);if(i>=0)arr[i]={...arr[i],...o};saveState('تم حفظ التعديل')}
 else if(currentType==='income'||currentType==='expense'||currentType==='vault'){state.transactions.push({id:uid(),type:currentType,...o}) ;saveState('تم التسجيل وظهر في الرئيسية')}
 else if(currentType==='fixed'){state.fixed.push({id:uid(),...o});saveState('تمت إضافة المصروف الثابت')}
 else if(currentType==='debt'){state.debts.push({id:uid(),...o,remaining:o.remaining});saveState('تمت إضافة الدين بدون خصمه من المتاح')}
 else if(currentType==='goal'){state.goals.push({id:uid(),...o});saveState('تم إنشاء الهدف')}
 closeAll()
};
function editItem(kind,id){let arr=arrOf(kind),x=arr.find(v=>v.id===id);if(!x)return;if(kind==='transaction'&&x.type==='debt_payment'&&x.debtId)return toast('تعديل دفعة الدين يتطلب تسوية المتبقي معها؛ راجع بند الدين.');currentType=kind==='transaction'?(['fixed_payment','debt_payment'].includes(x.type)?'expense':x.type):kind;editRef={kind,id};$('formTitle').textContent='تعديل '+(typeLabels[currentType]||'البند');$('formFields').innerHTML=schemas[currentType].map(f=>fieldHTML(f,x[f[0]]??'')).join('');$('formOverlay').classList.add('show')}
function deleteItem(kind,id){if(!confirm('حذف هذا البند؟'))return;let key=keyOf(kind);state[key]=state[key].filter(x=>x.id!==id);saveState('تم الحذف')}
function fixedActual(id){return state.transactions.filter(t=>appliesDate(t.date)&&t.type==='fixed_payment'&&t.fixedId===id).reduce((s,t)=>s+Number(t.amount||0),0)}
function payFixed(id){let x=state.fixed.find(v=>v.id===id);if(!x)return;let prev=fixedActual(id),raw=prompt('كم كان الصرف الفعلي لهذا الشهر؟',prev||x.amount);if(raw===null)return;let amt=Number(raw);if(!(amt>=0)){toast('أدخل مبلغًا صحيحًا');return}state.transactions=state.transactions.filter(t=>!(t.type==='fixed_payment'&&t.fixedId===id&&String(t.date||'').slice(0,7)===monthKey()));if(amt>0)state.transactions.push({id:uid(),type:'fixed_payment',fixedId:id,name:x.name,amount:amt,date:monthKey()+'-'+String(Math.min(new Date().getDate(),28)).padStart(2,'0')});saveState('تم تسجيل الفعلي وتحديث النسبة والفرق')}
function payDebt(id){let x=state.debts.find(v=>v.id===id);if(!x)return;let amt=Number(prompt('كم دفعت من القسط؟',Math.min(x.monthly||x.remaining,x.remaining)));if(!(amt>0))return;amt=Math.min(amt,x.remaining);x.remaining=Math.max(0,x.remaining-amt);if(x.installments>0)x.installments=Math.max(0,x.installments-1);state.transactions.push({id:uid(),type:'debt_payment',debtId:id,name:'دفعة '+x.name,amount:amt,date:currentDate()});saveState('تم تسجيل القسط وتحديث المتبقي')}
function localAdvice(){let t=totals(),msg=!t.income?'ابدأ بتسجيل دخلك لهذا الشهر، وبعدها أقدر أقارن المصروفات بالمتاح.':t.available<0?`عندك عجز حالي ${fmt(Math.abs(t.available))}. راجع المصروفات المسجلة قبل إضافة التزامات جديدة.`:`المتاح الحالي ${fmt(t.available)}، وإجمالي الدين المتبقي ${fmt(t.debt)}. هذه قراءة محلية وليست اتصالًا بذكاء اصطناعي خارجي.`;$('answer').textContent=msg}
function openDrawer(){$('drawer').classList.add('show');$('drawerBackdrop').classList.add('show')}function closeDrawer(){$('drawer').classList.remove('show');$('drawerBackdrop').classList.remove('show')}
$('menuBtn').onclick=openDrawer;$('drawerBackdrop').onclick=closeDrawer;$('fab').onclick=openTypes;$('bellBtn').onclick=()=>toast($('alertBox').textContent);$('prevBtn').onclick=()=>{state.offset--;saveState()};$('nextBtn').onclick=()=>{state.offset++;saveState()};
$('quickTypes').innerHTML=Object.entries(typeLabels).map(([k,v])=>`<button onclick="chooseType('${k}')">${v}</button>`).join('');
const keyOf=k=>({transaction:'transactions',fixed:'fixed',debt:'debts',goal:'goals'}[k]),arrOf=k=>state[keyOf(k)];
const SPENT=['expense','fixed_payment','debt_payment','vault'];
function chart6(){const offset=state.offset||0,M=[];try{for(let i=5;i>=0;i--){state.offset=offset-i;let c=cycle(),t=totals();M.push({l:c.start.slice(5),i:t.income,o:t.expenses})}}finally{state.offset=offset}const mx=Math.max(1,...M.flatMap(m=>[m.i,m.o]));return `<svg role="img" aria-label="الدخل والمدفوعات والتحويلات لآخر ست دورات راتب" viewBox="0 0 320 140" style="width:100%">${M.map((m,k)=>{const x=k*53+8,a=m.i/mx*100,b=m.o/mx*100;return `<g><title>${m.l}: الدخل ${fmt(m.i)} والخارج ${fmt(m.o)}</title><rect x="${x}" y="${110-a}" width="18" height="${a}" rx="4" fill="#86c6af"/><rect x="${x+21}" y="${110-b}" width="18" height="${b}" rx="4" fill="#a9bccf"/><text x="${x+20}" y="128" fill="#a4afbc" font-size="10" text-anchor="middle">${m.l}</text></g>`}).join('')}</svg>`}

function extra(){
{const t=totals(),saved=state.goals.reduce((a,g)=>a+goalBalance(g.id),0),plan=t.upcomingFixed+t.upcomingDebt,left=t.income-plan,net=saved-t.debt;
$('ovw').innerHTML=`<div><small>الدين المتبقي</small><b style="color:var(--red)">${fmt(t.debt)}</b></div><div><small>المدخر بالخزائن</small><b style="color:var(--green)">${fmt(saved)}</b></div><div><small>الخزائن ناقص الدين</small><b style="color:${net<0?'var(--red)':'var(--green)'}">${fmt(net)}</b></div>`;
$('plan').innerHTML=t.income?`<b>خطة الشهر:</b> التزاماتك المجدولة ${fmt(plan)} من دخل ${fmt(t.income)} — يتبقى بعدها <b>${fmt(left)}</b>${left<0?' (عجز، راجع الالتزامات)':''}.`:'<b>خطة الشهر:</b> سجّل دخل الشهر ليظهر لك الباقي بعد الالتزامات.'}
$('txs').innerHTML=state.transactions.filter(x=>appliesDate(x.date)).sort((a,b)=>String(b.date).localeCompare(a.date)).slice(0,6).map(x=>`<div class="row"><div><strong>${esc(x.name)}</strong><br><small>${esc(x.date)}</small></div><div class="amt" style="color:${x.type==='income'?'var(--green)':'var(--text)'}">${x.type==='income'?'+':'−'}${fmt(x.amount)}</div></div>`).join('')||'<div class="empty">لا حركات هذا الشهر.</div>';
const tot=state.debts.reduce((s,x)=>s+x.total,0),rem=state.debts.reduce((s,x)=>s+Math.max(0,x.remaining),0),mon=state.debts.reduce((s,x)=>s+(x.remaining>0?Math.min(x.monthly,x.remaining):0),0),pc=tot?Math.round((1-rem/tot)*100):0;
$('debtsPage').insertAdjacentHTML('afterbegin',`<div class="card" style="margin-bottom:12px"><div class="label">إجمالي الدين المتبقي</div><div class="value">${fmt(rem)}</div><div class="progress"><i style="width:${pc}%"></i></div><small class="label">سُدد ${pc}٪ • أقساط شهرية ${fmt(mon)} • مدة السداد تعتمد على جدول كل دين؛ لا تشمل فوائد أو رسومًا مستقبلية</small></div>`);
$('reportsPage').insertAdjacentHTML('beforeend',`<div class="card" style="margin-top:12px"><h3 style="margin:0 0 8px;font-size:14px">آخر ٦ دورات راتب</h3>${chart6()}<small class="label"><span style="color:var(--green)">●</span> دخل &nbsp; <span style="color:var(--gold)">●</span> خارج</small></div>`);
$('settingsPage').insertAdjacentHTML('beforeend',`<div class="card" style="margin-top:12px"><h3 style="margin:0 0 4px;font-size:14px">النسخ الاحتياطي</h3><p class="label">بياناتك على هذا الجهاز فقط. صدّر نسخة قبل أي تغيير أو نقل لرابط جديد.</p><div class="actions"><button onclick="exportData()">تصدير</button><button onclick="importData()">استيراد</button></div></div>`)}
const _render=render;render=function(){_render();extra()};
function exportData(){const j=JSON.stringify(state,null,1),n='mali-backup-'+currentDate()+'.json',f=new File([j],n,{type:'application/json'});if(navigator.canShare&&navigator.canShare({files:[f]})){navigator.share({files:[f]}).catch(()=>{});return}const a=document.createElement('a');a.href=URL.createObjectURL(f);a.download=n;a.click()}
function importData(){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=async()=>{try{const d=JSON.parse(await i.files[0].text());if(!d.transactions||!d.fixed||!d.debts||!d.goals)throw 0;state=d;saveState('تم الاستيراد')}catch(e){toast('ملف غير صالح')}};i.click()}
if(navigator.storage&&navigator.storage.persist)navigator.storage.persist();
// V7: dates are civil dates in Riyadh; no automatic payments or income.
function currentDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function dateParts(s){return s.split('-').map(Number)}
function civil(y,m,d){return `${y}-${String(m).padStart(2,'0')}-${String(Math.min(d,new Date(y,m,0).getDate())).padStart(2,'0')}`}
function monthDate(){let [y,m,d]=dateParts(currentDate());let day=state.settings.salaryDay||27;return new Date(y,m-1+(d<Math.min(day,new Date(y,m,0).getDate())?-1:0)+(state.offset||0),1)}
function cycle(){let d=monthDate(),y=d.getFullYear(),m=d.getMonth()+1,day=state.settings.salaryDay||27,next=new Date(y,m,1);return {start:civil(y,m,day),end:civil(next.getFullYear(),next.getMonth()+1,day)}}
function appliesDate(date){let c=cycle();return typeof date==='string'&&date>=c.start&&date<c.end}
function recurringApplies(x){return !x.startDate||dueInCycle(x.dueDay||27)>=x.startDate}
function matchedFixed(t,x){return t.type==='fixed_payment'&&(t.fixedId===x.id||(!t.fixedId&&t.name===x.name))}
function fixedActual(id){let x=state.fixed.find(x=>x.id===id);return x?state.transactions.filter(t=>appliesDate(t.date)&&matchedFixed(t,x)).reduce((a,t)=>a+Number(t.amount),0):0}
function dueInCycle(day){let c=cycle(),[y,m]=dateParts(c.start),ds=civil(y,m,day);if(ds<c.start){let n=new Date(y,m,1);ds=civil(n.getFullYear(),n.getMonth()+1,day)}return ds}
function commitments(){return [...state.fixed.filter(recurringApplies).map(x=>({name:x.name,amount:Math.max(0,x.amount-fixedActual(x.id)),date:dueInCycle(x.dueDay||27),kind:'ثابت'})),...state.debts.filter(x=>x.remaining>0&&x.monthly>0&&(!x.dueDate||x.dueDate<cycle().end)).map(x=>({name:x.name,amount:Math.max(0,Math.min(x.monthly,x.remaining)-state.transactions.filter(t=>t.debtId===x.id&&t.type==='debt_payment'&&appliesDate(t.date)).reduce((a,t)=>a+t.amount,0)),date:x.dueDate||'غير محدد',kind:'قسط'}))].filter(x=>x.amount>0).sort((a,b)=>a.date.localeCompare(b.date))}
function totals(){let tx=state.transactions.filter(x=>appliesDate(x.date)),sum=types=>tx.filter(x=>types.includes(x.type)).reduce((a,x)=>a+Number(x.amount),0),income=sum(['income']),expenses=sum(['expense','fixed_payment','debt_payment','vault']),fixed=state.fixed.filter(recurringApplies).reduce((a,x)=>a+x.amount,0),debtPlan=state.debts.filter(x=>x.remaining>0&&(!x.dueDate||x.dueDate<cycle().end)).reduce((a,x)=>a+Math.min(x.monthly,x.remaining),0);return {tx,income,expenses,available:income-expenses,debt:state.debts.reduce((a,x)=>a+Math.max(0,x.remaining),0),upcomingFixed:fixed,upcomingDebt:debtPlan,unpaid:commitments().reduce((a,x)=>a+x.amount,0),spending:sum(['expense','fixed_payment','debt_payment']),transfers:sum(['vault'])}}
function validateState(d){if(!d||typeof d!=='object')throw Error('صيغة غير صالحة');for(let key of ['transactions','fixed','debts','goals']){if(!Array.isArray(d[key]))throw Error('قائمة ناقصة: '+key);let ids=new Set();for(let x of d[key]){if(!x||typeof x.id!=='string'||!/^[a-zA-Z0-9_-]+$/.test(x.id)||ids.has(x.id))throw Error('معرف بند غير صالح أو مكرر');ids.add(x.id);if(typeof x.name!=='string')throw Error('اسم بند غير صالح');for(let f of ['amount','total','remaining','monthly','initial','target','installments'])if(x[f]!=null&&(!Number.isFinite(x[f])||x[f]<0))throw Error('مبلغ غير صالح');for(let f of ['date','startDate','dueDate','targetDate'])if(x[f]&&!validDate(x[f]))throw Error('تاريخ غير صالح');if(key==='transactions'&&!['income','expense','vault','fixed_payment','debt_payment'].includes(x.type))throw Error('نوع حركة غير معروف')}}if(!d.settings||!Number.isInteger(d.settings.salaryDay)||d.settings.salaryDay<1||d.settings.salaryDay>31)throw Error('يوم الراتب غير صالح');if(d.offset!=null&&!Number.isInteger(d.offset))throw Error('الفترة غير صالحة');return d}
function validDate(s){if(typeof s!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;let [y,m,d]=dateParts(s);return m>=1&&m<=12&&d>=1&&d<=new Date(y,m,0).getDate()}
let lastSaved=JSON.stringify(state);
function saveState(msg){try{validateState(state);let json=JSON.stringify(state);if(json!==lastSaved){localStorage.setItem('mali-v7-undo',lastSaved);localStorage.setItem('mali-v4',json);lastSaved=json}render();if(msg)toast(msg)}catch(e){state=JSON.parse(lastSaved);render();toast('لم يُحفظ التغيير: '+e.message)}}
function undoChange(){let raw=localStorage.getItem('mali-v7-undo');if(!raw)return toast('لا توجد نسخة تراجع');if(!confirm('استعادة البيانات قبل آخر تغيير محفوظ؟'))return;try{let old=validateState(JSON.parse(raw));state=old;saveState('تمت الاستعادة')}catch(e){toast('تعذر الاستعادة')}}
function validate(o){if(currentType!=='vault'&&!o.name)return 'اكتب اسم البند';for(let f of schemas[currentType]){if(f[2]==='number'&&(!Number.isFinite(o[f[0]])||o[f[0]]<0))return 'أدخل أرقامًا موجبة وصحيحة';if(f[2]==='date'&&o[f[0]]&&!validDate(o[f[0]]))return 'تحقق من التاريخ'}if(['income','expense','vault'].includes(currentType)&&!o.date)return 'اختر التاريخ';if(['income','expense','fixed','vault'].includes(currentType)&&!(o.amount>0))return 'أدخل مبلغًا أكبر من صفر';if(currentType==='fixed'&&(!Number.isInteger(o.dueDay)||o.dueDay<1||o.dueDay>31))return 'يوم الاستحقاق من 1 إلى 31';if(currentType==='debt'&&(o.total<=0||o.remaining>o.total||!Number.isInteger(o.installments)))return 'تحقق من الإجمالي والمتبقي وعدد الأقساط';if(currentType==='vault'&&!state.goals.some(x=>x.id===o.goalId))return 'اختر خزينة موجودة';return ''}
function payFixed(id){let x=state.fixed.find(x=>x.id===id);if(!x)return;let raw=prompt('إجمالي المدفوع لهذا البند في الدورة المختارة (يستبدل الفعلي السابق):',fixedActual(id)||x.amount);if(raw===null)return;let amount=Number(raw);if(!raw.trim()||!Number.isFinite(amount)||amount<0)return toast('المبلغ غير صالح');let c=cycle(),date=appliesDate(currentDate())?currentDate():c.start;state.transactions=state.transactions.filter(t=>!(appliesDate(t.date)&&matchedFixed(t,x)));state.transactions.push({id:uid(),type:'fixed_payment',fixedId:id,name:x.name,amount,date});saveState('تم تسجيل الفعلي')}
function payDebt(id){let x=state.debts.find(x=>x.id===id);if(!x||x.remaining<=0)return toast('لا يوجد رصيد متبقٍ');let raw=prompt('المبلغ المدفوع فعليًا (لا تتغير مواعيد القسط أو عدد الأقساط تلقائيًا):',Math.min(x.monthly||x.remaining,x.remaining));if(raw===null)return;let amount=Number(raw);if(!Number.isFinite(amount)||amount<=0||amount>x.remaining)return toast('المبلغ يجب أن يكون أكبر من صفر ولا يتجاوز المتبقي');let date=prompt('تاريخ الدفع الفعلي YYYY-MM-DD',appliesDate(currentDate())?currentDate():cycle().start);if(date===null)return;if(!validDate(date))return toast('تاريخ غير صالح');x.remaining=Math.round((x.remaining-amount)*100)/100;state.transactions.push({id:uid(),type:'debt_payment',debtId:id,name:'دفعة '+x.name,amount,date});saveState('تم تسجيل الدفع؛ راجع موعد القسط التالي من التعديل')}
function deleteItem(kind,id){if(kind==='goal'&&state.transactions.some(x=>x.goalId===id))return toast('الخزينة مرتبطة بحركات؛ عدّلها بدل حذف سجلها');if(kind==='transaction'){let x=state.transactions.find(x=>x.id===id);if(x?.type==='debt_payment'&&x.debtId){return toast('لإلغاء دفعة دين: عدّل المتبقي والدفعة معًا؛ لا يمكن حذفها وحدها')}}if(!confirm('حذف البند المحدد؟ يحتفظ البرنامج بنسخة تراجع قبل الحذف.'))return;state[keyOf(kind)]=state[keyOf(kind)].filter(x=>x.id!==id);saveState('تم الحذف')}
function audit(){let list=[];let unlinked=state.transactions.filter(x=>['fixed_payment','debt_payment'].includes(x.type)&&!x.fixedId&&!x.debtId);if(unlinked.length)list.push(`${unlinked.length} مدفوعات قديمة بدون معرف بند. طابقت أسماء الثابتة عند الحساب فقط؛ دفعة القروض المجمعة تحتاج مراجعتك.`);for(let x of state.debts){if(x.dueDate&&x.dueDate<currentDate()&&x.remaining>0)list.push(`استحقاق ${x.name} بتاريخ ${x.dueDate} مضى؛ تحقق من الدفع والموعد القادم.`);if(x.installments&&Math.abs(x.installments*x.monthly-x.remaining)>1)list.push(`${x.name}: حاصل عدد الأقساط × القسط يختلف عن المتبقي؛ راجع الأرقام.`)}return list}
const renderV7=render;render=function(){renderV7();let c=cycle(),t=totals(),end=new Date(c.end+'T12:00:00');end.setDate(end.getDate()-1);let endStr=civil(end.getFullYear(),end.getMonth()+1,end.getDate());$('monthLabel').textContent=`${c.start} ← ${endStr}`;$('cycleCaption').textContent='الفترة المختارة من '+c.start+' إلى '+endStr;$('upcoming').textContent=fmt(t.unpaid);if(t.available-t.unpaid<0){$('status').className='status pressure';$('status').textContent='هامش سالب'}else if(!t.income){$('status').className='status attention';$('status').textContent='الدخل غير مسجل'}$('heroText').textContent='قراءة دورة الراتب المحددة؛ السداد والدخل يُسجلان يدويًا.';let [y,m,d]=dateParts(currentDate()),day=state.settings.salaryDay,next=civil(y,m,day);if(next<currentDate()){let n=new Date(y,m,1);next=civil(n.getFullYear(),n.getMonth()+1,day)}$('salaryDays').textContent=Math.round((Date.parse(next)-Date.parse(currentDate()))/86400000)+' يوم';$('plan').innerHTML=`<b>هامش الدورة بعد الالتزامات غير المدفوعة:</b> ${fmt(t.available-t.unpaid)}<br><span class="muted">صافي المسجل ${fmt(t.available)} − التزامات متبقية ${fmt(t.unpaid)}. لا يمثل هذا رصيد البنك؛ أرصدة البداية والمصروفات غير المسجلة غير مشمولة.</span>`;$('alertBox').textContent=t.income?`المدفوعات ${fmt(t.spending)} والتحويلات للخزائن ${fmt(t.transfers)}. راجع الاستحقاقات قبل اعتبار الصافي متاحًا للصرف.`:'لم تسجل دخلًا في هذه الدورة؛ تكرار الراتب لا يُعد إيداعًا فعليًا.';$('recent').innerHTML=commitments().slice(0,6).map(x=>`<div class="row"><div><strong>${esc(x.name)}</strong><br><small>${esc(x.date)} • ${x.kind}</small></div><b>${fmt(x.amount)}</b></div>`).join('')||'<div class="empty">لا توجد التزامات غير مدفوعة وفق السجل.</div>';
$('goals').innerHTML=state.goals.map(g=>{let b=goalBalance(g.id),pct=g.target?Math.min(100,Math.max(0,b/g.target*100)):0;return `<div class="goal"><strong>${esc(g.name)}</strong>${g.target?`<div class="progress"><i style="width:${pct}%"></i></div><small>${fmt(b)} من ${fmt(g.target)} • ${pct.toFixed(0)}٪</small>`:`<div class="value">${fmt(b)}</div><small>خزينة بدون مبلغ مستهدف</small>`}</div>`}).join('');
$('settingsPage').insertAdjacentHTML('beforeend',`<div class="card section"><h3>استعادة ومراجعة</h3><p class="muted">نسخة تلقائية قبل آخر تغيير. النسخ المصدّرة تحتوي بيانات مالية شخصية.</p><div class="actions"><button onclick="undoChange()">تراجع عن آخر تغيير</button><button onclick="window.print()">طباعة الصفحة</button></div></div>`);$('reportsPage').insertAdjacentHTML('beforeend',`<div class="card section"><h3>مراجعة جودة البيانات</h3>${audit().map(x=>`<div class="audit">${esc(x)}</div>`).join('')||'<p>لم تُرصد تناقضات ضمن فحوص المراجعة الحالية.</p>'}</div>`);
$('reportsPage').insertAdjacentHTML('beforeend',`<div class="section"><div class="sectionhead"><h3>سجل حركات الدورة</h3></div><div class="list">${t.tx.map(x=>`<div class="row"><div><strong>${esc(x.name)}</strong><br><small>${esc(x.date)} • ${esc(x.type==='income'?'دخل':x.type==='vault'?'تحويل ادخار':'مدفوعات')}</small></div><b>${fmt(x.amount)}</b>${actionButtons('transaction',x.id)}</div>`).join('')||'<div class="empty">لا حركات مسجلة</div>'}</div></div>`);
for(let id of ['incomePage','variablePage','fixedPage','debtsPage','goalsPage']){let input=document.createElement('input');input.className='search';input.placeholder='بحث في البنود…';input.setAttribute('aria-label','بحث في البنود');input.oninput=()=>$(id).querySelectorAll('.row,.fixedItem').forEach(el=>el.hidden=!el.textContent.includes(input.value));$(id).insertBefore(input,$(id).querySelector('.list'))}
$('settingsPage').querySelector('input[type=number]').onchange=function(){let n=Number(this.value);if(!Number.isInteger(n)||n<1||n>31)return toast('اليوم من 1 إلى 31');state.settings.salaryDay=n;saveState()};renderCalendar()};
function goalBalance(id){let g=state.goals.find(x=>x.id===id);return Number(g?.initial||0)+state.transactions.filter(x=>x.type==='vault'&&x.goalId===id&&x.date<cycle().end).reduce((a,x)=>a+Number(x.amount),0)}
function renderCalendar(){let c=cycle(),d=new Date(c.start+'T12:00:00'),cells=['أحد','اثنين','ثلاثاء','أربعاء','خميس','جمعة','سبت'].map(x=>`<div class="calHead">${x}</div>`).join('');for(let i=0;i<d.getDay();i++)cells+='<div></div>';while(true){let ds=civil(d.getFullYear(),d.getMonth()+1,d.getDate());if(ds>=c.end)break;let ev=state.transactions.filter(x=>x.date===ds);let dues=commitments().filter(x=>x.date===ds);cells+=`<div class="day ${ds===currentDate()?'today':''}" title="${ds}"><b>${d.getDate()}/${d.getMonth()+1}</b>${state.settings.hijri?`<i class="hj">${new Intl.DateTimeFormat('ar-SA-u-ca-islamic-umalqura',{day:'numeric',month:'short'}).format(d)}</i>`:''}${ev.map(x=>`<div class="dot">${esc(x.name)}</div>`).join('')}${dues.map(x=>`<div class="dot" style="color:var(--amber)">استحقاق ${esc(x.name)}</div>`).join('')}</div>`;d.setDate(d.getDate()+1)}$('calendarPage').innerHTML='<div class="sectionhead"><h3>تقويم دورة الراتب</h3></div><p class="muted">الأزرق: حركة مسجلة • الذهبي: التزام غير مدفوع</p><div class="calendar">'+cells+'</div>'}
function importData(){let i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=async()=>{try{if(!i.files.length)return;if(i.files[0].size>5000000)throw Error('الملف كبير جدًا');let d=validateState(JSON.parse(await i.files[0].text()));if(!confirm('استبدال بيانات الجهاز بالنسخة المختارة؟ سيتم حفظ نسخة تراجع.'))return;state=d;saveState('تم الاستيراد')}catch(e){toast('لم يستورد الملف: '+e.message)}};i.click()}
function localAdvice(){let t=totals();$('answer').textContent=`الدخل المسجل ${fmt(t.income)}، المدفوعات ${fmt(t.spending)}، والتحويلات للخزائن ${fmt(t.transfers)}. هامش الدورة بعد غير المدفوع ${fmt(t.available-t.unpaid)}. ${audit().length} ملاحظات تحتاج مراجعة في التقارير. لا يشمل التحليل رسوم القروض أو أرصدة البنك غير المسجلة.`}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeAll();closeDrawer()}});document.querySelectorAll('.overlay').forEach(el=>el.addEventListener('click',e=>{if(e.target===el)closeAll()}));$('formOverlay').setAttribute('role','dialog');$('formOverlay').setAttribute('aria-modal','true');$('formOverlay').setAttribute('aria-labelledby','formTitle');

render();
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js?v=7').then(r=>r.update()).catch(()=>{})}
