// User-confirmed distribution. No changes to money, dates or payment history.
const bankProviders={urpay:{name:'urpay',logo:'urpay.webp'},vision:{name:'بنك فيجن',logo:'vision.svg'},rajhiTransfer:{name:'تحويل • الراجحي',symbol:'⇄'},stc:{name:'stc',logo:'stc.svg'},jazira:{name:'بنك الجزيرة',logo:'jazira.svg'},sadad:{name:'سداد / تحويل',symbol:'↗'},snb:{name:'الأهلي',logo:'snb.svg'},ehsan:{name:'إحسان',logo:'ehsan.svg'},emkan:{name:'إمكان',logo:'emkan.svg'},tabby:{name:'تابي',logo:'tabby.svg'},tamara:{name:'تمارا',logo:'tamara.svg'},bilad:{name:'بنك البلاد',logo:'bilad.png'}};
bankLabel=function(x){return bankProviders[x.bankProvider]?.name||(x.bankProvider==='custom'?String(x.bankName||'جهة مخصصة').slice(0,60):'')};
bankLogo=function(x){return safeBankLogo(x.bankLogo)||(bankProviders[x.bankProvider]?.logo?'./assets/'+bankProviders[x.bankProvider].logo:'')};
bankBadge=function(x){let name=bankLabel(x);if(!name)return '';let logo=bankLogo(x),symbol=bankProviders[x.bankProvider]?.symbol;return `<span class="bankBadge bank-${esc(x.bankProvider||'custom')}">${logo?`<img src="${logo}" alt="${esc(name)}" width="62" height="23">`:symbol?`<span class="transferMark" aria-hidden="true">${symbol}</span>`:''}<span>${esc(name)}</span></span>`};
let providerOptions='غير محددة|,'+Object.entries(bankProviders).map(([key,p])=>`${p.name}|${key}`).join(',')+',جهة أخرى|custom';
for(let kind of ['fixed','debt','goal']){let existing=schemas[kind].find(f=>f[0]==='bankProvider');if(existing)existing[3]=providerOptions;else schemas[kind].push(['bankProvider','جهة الصرف / الحفظ','select',providerOptions],['bankName','اسم الجهة الأخرى (اختياري)','text'],['bankLogo','شعار الجهة الأخرى','bankLogo'],['bankDisplay','عرض الشعار','select','شعار بجانب الاسم|badge,بانر خفيف خلف البند|banner'])}
// Replace the former urpay-only check while retaining base financial validation.
validate=function(o){let err=validateBeforeBank(o);if(err)return err;if(['fixed','debt','goal'].includes(currentType)){if(o.bankProvider&&!bankProviders[o.bankProvider]&&o.bankProvider!=='custom')return 'جهة غير صالحة';if(o.bankProvider==='custom'&&!o.bankName?.trim())return 'اكتب اسم الجهة';if(String(o.bankName||'').length>60)return 'اسم الجهة طويل';if(o.bankLogo&&!safeBankLogo(o.bankLogo))return 'شعار غير صالح'}return ''};
function applyBankDistribution(d){if(d.bankDistributionRevision==='2026-10-04-v1')return d;let fixed={ 'f-house':'urpay','f-kids':'vision','f-wife':'rajhiTransfer','f-wife-mobile':'stc','f-electric':'jazira','f-water':'jazira','f-uni':'sadad','f-personal':'snb','f-charity':'ehsan','f-entertainment':'snb'};for(let [id,provider] of Object.entries(fixed)){let x=d.fixed.find(x=>x.id===id);if(x)Object.assign(x,{bankProvider:provider,bankDisplay:'badge',bankLogo:'',bankName:''})}let council=d.goals.find(g=>g.id==='g-majlis');if(council)Object.assign(council,{bankProvider:'bilad',bankDisplay:'badge',bankLogo:'',bankName:''});for(let x of d.debts){let provider=x.id==='d3'&&x.monthly===237?'emkan':/^تابي/.test(x.name)?'tabby':/^تمارا/.test(x.name)?'tamara':'';if(provider)Object.assign(x,{bankProvider:provider,bankDisplay:'badge',bankLogo:'',bankName:''})}d.bankDistributionRevision='2026-10-04-v1';return d}
if(state.bankDistributionRevision!=='2026-10-04-v1'){let before=JSON.stringify(state);try{let updated=applyBankDistribution(structuredClone(state));validateState(updated);localStorage.setItem('mali-banks-before-20261004',before);localStorage.setItem('mali-v7-undo',before);localStorage.setItem('mali-v4',JSON.stringify(updated));state=updated;lastSaved=JSON.stringify(state)}catch(e){toast('تعذر حفظ توزيع الجهات: '+e.message)}}
const renderBeforeProviderBadges=render;render=function(){renderBeforeProviderBadges();for(let [page,kind] of [['debtsPage','debt'],['goalsPage','goal']]){let arr=arrOf(kind);$(page).querySelectorAll('button[onclick]').forEach(button=>{let action=button.getAttribute('onclick')||'',match=action.match(new RegExp("editItem\\('"+kind+"','([A-Za-z0-9_-]+)'\\)"));if(!match)return;let x=arr.find(x=>x.id===match[1]),badge=x&&bankBadge(x);if(badge){let row=button.closest('.goalPlanRow');if(row&&!row.querySelector('.bankBadge'))row.insertAdjacentHTML('afterbegin',badge)}})}};
render();

// Account envelopes cover assigned fixed items, installments and goal allocations.
bankDistribution=function(){let entries=[...state.fixed.filter(recurringApplies).map(x=>({item:x,planned:x.amount,actual:fixedActual(x.id)})),...state.debts.filter(x=>cycleDebtAmount(x)>0).map(x=>({item:x,planned:cycleDebtAmount(x),actual:state.transactions.filter(t=>appliesDate(t.date)&&t.type==='debt_payment'&&t.debtId===x.id).reduce((a,t)=>a+t.amount,0)})),...state.goals.filter(x=>goalMonthlyAllocation(x)>0).map(x=>({item:x,planned:goalMonthlyAllocation(x),actual:state.transactions.filter(t=>appliesDate(t.date)&&t.type==='vault'&&t.goalId===x.id).reduce((a,t)=>a+t.amount,0)}))];let grouped=new Map();for(let e of entries){let key=bankLabel(e.item)||'غير موزع';if(!grouped.has(key))grouped.set(key,{name:key,planned:0,actual:0,count:0,item:e.item});let b=grouped.get(key);b.planned+=e.planned;b.actual+=e.actual;b.count++}return [...grouped.values()]};
