/* V8 dashboard is a read-only projection; existing edit and payment paths are reused. */
let dashboardMode='plan';
const dashboardIcons={home:'<path d="m3 10 9-7 9 7v10H3Z"/><path d="M9 20v-7h6v7"/>',expense:'<rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 8h6M9 12h6M9 16h3"/>',goal:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',bank:'<path d="m3 7 9-4 9 4M3 20h18M5 10v7M10 10v7M15 10v7M20 10v7"/>',edit:'<path d="m4 16 12-12 4 4L8 20H4Z"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>'};
function dashIcon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${dashboardIcons[name]||dashboardIcons.expense}</svg>`}
function dashNumber(n){return Number(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}
function dashboardFigures(){let f=surplusFigures(),t=totals(),salary=Number(state.incomePlan?.salary||0),citizen=Number(state.incomePlan?.citizen||0),obligations=f.fixedPlan+f.debtPlan;return {salary,citizen,obligations,goals:f.goalPlan,surplus:salary-obligations-f.goalPlan,withCitizen:f.planned,actual:t.available,income:t.income,spending:t.spending,transfers:t.transfers,unreserved:f.unreserved,unpaid:t.unpaid}}
function dashboardFlow(income,amounts){let positive=amounts.map(n=>Math.max(0,n)),total=Math.max(income,positive.reduce((a,n)=>a+n,0),1),height=110,start=25,paths='',target=10;positive.forEach((n,i)=>{let h=n/total*height;if(!h)return;let y=start,ty=target;paths+=`<path class="flowBand flow${i}" d="M 295 ${y} C 215 ${y},195 ${ty},72 ${ty} L72 ${ty+h} C195 ${ty+h},215 ${y+h},295 ${y+h} Z"/>`;start+=h;target+=h+15});return `<svg class="salaryFlow" viewBox="0 0 325 165" role="img" aria-label="توزيع المبلغ: ${positive.map(n=>fmt(n)).join('، ')}"><rect x="295" y="25" width="10" height="110" rx="4" class="flowSource"/>${paths}</svg>`}
function setDashboardMode(mode){if(!['plan','actual','accounts'].includes(mode))return;dashboardMode=mode;renderDashboard();document.querySelectorAll('.bottomNav button[data-page]').forEach(b=>b.classList.toggle('selected',b.getAttribute('data-page')===(mode==='accounts'?'accounts':'home')))}
function dashboardHome(mode='plan'){show('home');setDashboardMode(mode)}
function dashboardExecution(){let active=state.fixed.filter(recurringApplies),ids=['f-house','f-entertainment'],items=ids.map(id=>active.find(x=>x.id===id)).filter(Boolean);for(let x of active){if(items.length>=2)break;if(!items.includes(x))items.push(x)}return items.map(x=>{let actual=fixedActual(x.id),has=state.transactions.some(t=>appliesDate(t.date)&&matchedFixed(t,x));return `<div class="executionRow ${x.bankDisplay==='banner'?'bankBanner':''}">${bankBackground(x)}<div class="executionName"><strong>${esc(x.name)}</strong>${bankBadge(x)}</div><button class="executionAmount" onclick="editItem('fixed','${x.id}')" aria-label="تعديل مخطط ${esc(x.name)}"><small>المخطط</small><b>${Number(x.amount).toLocaleString('en-US')}</b></button><button class="executionAmount" onclick="payFixed('${x.id}')" aria-label="تعديل الفعلي ${esc(x.name)}"><small>الفعلي</small><b>${has?Number(actual).toLocaleString('en-US'):'—'}</b></button><button class="iconEdit" onclick="payFixed('${x.id}')" aria-label="تسجيل فعلي ${esc(x.name)}">${dashIcon('edit')}</button></div>`}).join('')||'<p class="dashNote">لا توجد مصاريف ثابتة في الدورة المختارة.</p>'}
function renderDashboard(){let d=dashboardFigures(),actual=dashboardMode==='actual',accounts=dashboardMode==='accounts',c=cycle(),end=addCivilMonths(c.start,0);let endDate=new Date(c.end+'T12:00:00');endDate.setDate(endDate.getDate()-1);end=civil(endDate.getFullYear(),endDate.getMonth()+1,endDate.getDate());$('dashboardPeriod').textContent=`دورة الراتب ${dateLabel(c.start)} — ${dateLabel(end)}`;$('monthLabel').textContent=new Intl.DateTimeFormat('ar-SA-u-ca-gregory-nu-latn',{month:'long',year:'numeric'}).format(monthDate());
$('dashboardTabs').innerHTML=[['plan','الخطة'],['actual','الفعلي'],['accounts','الحسابات']].map(([id,label])=>`<button role="tab" aria-selected="${dashboardMode===id}" aria-controls="dashboardPanel" onclick="setDashboardMode('${id}')">${label}</button>`).join('');
let hero=actual?d.actual:d.surplus;$('dashboardLabel').textContent=actual?'الفائض حسب المسجل':'الفائض المخطط • الراتب فقط';$('dashboardAmount').textContent=dashNumber(hero);$('dashboardAmount').classList.toggle('negative',hero<0);$('dashboardSubtitle').textContent=actual?'الدخل المسجل ناقص المدفوعات والتحويلات':'بعد الالتزامات ومخصصات الأهداف';
$('dashboardStats').innerHTML=actual?`<div><small>دخل مسجل</small><b>${fmt(d.income)}</b></div><div><small>مدفوعات وتحويلات</small><b>${fmt(d.spending+d.transfers)}</b></div>`:`<div><small>الدخل المخطط</small><b>${fmt(d.salary)}</b></div><div><small>الالتزامات</small><b>${fmt(d.obligations)}</b></div>`;
let figures=surplusFigures();let breakdown=actual?[
 ['دخل مسجل',d.income,'+'],['مصروفات ودفعات مسجلة',d.spending,'−'],['تحويلات للأهداف',d.transfers,'−'],['الفائض حسب المسجل',d.actual,'=']
]:[['الراتب المخطط',d.salary,'+'],['المصاريف الثابتة',figures.fixedPlan,'−'],['الأقساط والديون',figures.debtPlan,'−'],['مخصصات الأهداف',d.goals,'−'],['الفائض المخطط',d.surplus,'=']];
$('dashboardFlow').innerHTML=breakdown.map(([label,value,sign],i)=>`<div class="planBreakdownRow ${i===breakdown.length-1?'planResult':''}"><span><i aria-hidden="true">${sign}</i>${label}</span><b class="${i===breakdown.length-1&&value<0?'negative':''}">${fmt(value)}</b></div>`).join('');
$('dashboardFlowTitle').textContent=actual?'كيف حُسب الفائض المسجل؟':'كيف توزّع راتب هذه الدورة؟';$('dashboardFlowSection').hidden=accounts;
let f=surplusFigures();$('dashboardDetails').innerHTML=actual?`<p>غير المحجوز حسب المسجل <b>${fmt(d.unreserved)}</b></p><p>التزامات غير مدفوعة ${fmt(d.unpaid)} · مخصصات أهداف لم تحول ${fmt(f.goalUnfunded)}.</p>${d.income===0?'<p>لم يسجل دخل لهذه الدورة؛ الصرف المسجل يظهر حتى لو لم تضف الدخل.</p>':''}`:`<p>الراتب ${fmt(d.salary)} − الثابتة ${fmt(f.fixedPlan)} − الأقساط ${fmt(f.debtPlan)} − الأهداف ${fmt(d.goals)} = ${fmt(d.surplus)}.</p><p>مع نزول حساب المواطن (${fmt(d.citizen)}) يصبح فائض الخطة ${fmt(d.withCitizen)}. الإيداع الفعلي لا يثبت إلا بالتسجيل.</p><p>رمضان محسوب حسب الجدول المعتمد. أي هدف غير ممول يظهر في مراقبة الخطة، ولا يُخصم مبلغه قبل تخصيصه.</p>`;
$('dashboardPlanNotice').textContent=c.start<state.settings.planStartDate?'الخطة المعتمدة تبدأ مع راتب '+dateLabel(state.settings.planStartDate):hero<0?'يوجد عجز في هذا العرض؛ راجع تفاصيل التوزيع.':'الخطة لا تمثل رصيد البنك؛ الفعلي يُسجل يدويًا.';
$('dashboardExecution').innerHTML=dashboardExecution();$('dashboardExecutionSection').hidden=accounts;$('dashboardAccountsSection').hidden=!accounts;
$('dashboardAccounts').innerHTML=bankDistribution().map(b=>`<div class="accountEnvelope"><div>${bankBadge(b.item,false)||`<strong>${esc(b.name)}</strong>`}<small>${b.count} بنود مخصصة</small></div><div><small>المخصص</small><b>${fmt(b.planned)}</b><small>فعلي ${fmt(b.actual)}</small></div><button class="mini" onclick="show('fixedPage')">البنود</button></div>`).join('');
let allocated=state.goals.filter(g=>goalMonthlyAllocation(g)>0);$('dashboardGoalsSummary').textContent=allocated.length?allocated.slice(0,2).map(g=>`${g.name} ${fmt(goalMonthlyAllocation(g))}`).join(' · '):'لا مخصصات أهداف لهذه الدورة';$('dashboardGoals').innerHTML=allocated.map(g=>{let paid=state.transactions.filter(t=>appliesDate(t.date)&&t.type==='vault'&&t.goalId===g.id).reduce((a,t)=>a+t.amount,0);return `<div class="dashGoal"><div><strong>${esc(g.name)}</strong>${bankBadge(g)}<small>مخصص ${fmt(goalMonthlyAllocation(g))} · محول ${fmt(paid)}</small><small>البداية ${dateLabel(g.planStartDate)}${g.targetDate?' · الموعد '+dateLabel(g.targetDate):''}</small></div><button class="mini" onclick="editItem('goal','${g.id}')">تعديل</button><button class="mini" onclick="chooseType('vault','${g.id}')">تحويل</button></div>`}).join('')+`<button class="textLink" onclick="show('goalsPage')">كل الأهداف ومواعيدها</button>`;
let investment=state.goals.find(g=>g.id==='g-investment');$('dashboardInvestment').innerHTML=investment?`<span>${investment.fundingStatus==='paused'?'الاستثمار مؤجل':investment.planStartDate>=c.end?'الاستثمار يبدأ '+dateLabel(investment.planStartDate):'مخصص الاستثمار '+fmt(goalMonthlyAllocation(investment))}</span><button class="textLink" onclick="editItem('goal','${investment.id}')">تعديل</button>`:'';
$('dashboardLedgerSection').hidden=dashboardMode!=='actual';$('dashboardHeroSection').hidden=accounts;$('dashboardTransactions').innerHTML=totals().tx.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3).map(t=>`<div class="dashTransaction"><div><strong>${esc(t.name)}</strong><small>${dateLabel(t.date)}</small></div><b>${t.type==='income'?'+':'−'}${fmt(t.amount)}</b></div>`).join('')||'<p class="dashNote">لا حركات مسجلة لهذه الدورة.</p>';
}
const renderBeforeDashboard=render;render=function(){renderBeforeDashboard();renderDashboard()};
const showBeforeDashboard=show;show=function(id){showBeforeDashboard(id);document.querySelectorAll('.bottomNav button[data-page]').forEach(b=>b.classList.toggle('selected',b.getAttribute('data-page')===id));};
$('bottomNav').innerHTML=[['home','الرئيسية','home',"dashboardHome()"],['fixedPage','المصاريف','expense',"show('fixedPage')"],['goalsPage','الأهداف','goal',"show('goalsPage')"],['accounts','الحسابات','bank',"dashboardHome('accounts')"],['more','المزيد','more','openDrawer()']].map(([id,label,icon,action])=>`<button data-page="${id}" class="${id==='home'?'selected':''}" onclick="${action}">${dashIcon(icon)}<span>${label}</span></button>`).join('');
renderDashboard();

$('bellBtn').onclick=()=>chooseType('expense');
