/* Seasonal deadlines are tentative calendar estimates, not payment confirmations. */
function applySeasonDates(d){if(d.seasonDatesRevision==='2026-10-04-v1')return d;for(let [id,date] of [['g-ramadan','2027-02-08'],['g-adha','2027-05-16']]){let g=d.goals.find(g=>g.id===id);if(g){if(!g.targetDate){g.targetDate=date;g.deadlineTentative=true}if(!g.planStartDate)g.planStartDate=d.settings.planStartDate||'2026-10-27';g.excludeDeadlineSalary=true}}d.seasonDatesRevision='2026-10-04-v1';return d}
if(state.seasonDatesRevision!=='2026-10-04-v1'){let before=JSON.stringify(state);try{let d=applySeasonDates(structuredClone(state));validateState(d);localStorage.setItem('mali-season-dates-before-20261004',before);localStorage.setItem('mali-v7-undo',before);localStorage.setItem('mali-v4',JSON.stringify(d));state=d;lastSaved=JSON.stringify(state)}catch(e){toast('تعذر حفظ مواعيد الأهداف: '+e.message)}}
function goalSalaryDates(g,asOf=currentDate()){if(!g.targetDate||!validDate(g.targetDate)||g.fundingStatus==='paused')return [];let start=[asOf,g.planStartDate||state.settings.planStartDate||asOf].sort().at(-1),[y,m]=dateParts(start),day=state.settings.salaryDay||27,dates=[];for(let i=0;i<240;i++){let month=new Date(y,m-1+i,1),date=civil(month.getFullYear(),month.getMonth()+1,day);if(date>g.targetDate||g.excludeDeadlineSalary&&date===g.targetDate)break;if(date>=start)dates.push(date)}return dates}
function goalFundingNeed(g,asOf=currentDate()){let dates=goalSalaryDates(g,asOf),remaining=Math.max(0,Number(g.target||0)-goalBalance(g.id));return {dates,count:dates.length,remaining,perSalary:dates.length?Math.ceil(remaining*100/dates.length)/100:0}}
function seasonalFundingRows(){let asOf=[currentDate(),cycle().start].sort().at(-1);return ['g-ramadan','g-adha'].map(id=>{let g=state.goals.find(g=>g.id===id);if(!g)return '';let n=goalFundingNeed(g,asOf);return `<div class="seasonalGoal"><div><strong>${esc(g.name)}</strong><small>الموعد ${dateLabel(g.targetDate)}${g.deadlineTentative?' (تقديري، حسب الرؤية)':''}</small><small>المتبقي للهدف ${fmt(n.remaining)} · ${n.count} رواتب متاحة قبل الموعد</small></div><div class="seasonalNeed"><b>${n.count?fmt(n.perSalary):n.remaining>0?'لا رواتب متاحة':'مكتمل'}</b><small>المطلوب لكل راتب</small></div><details><summary>الرواتب وتعديل الموعد</summary><p>${n.dates.length?n.dates.map(dateLabel).join(' · '):'لا رواتب متاحة من بداية الحساب قبل الموعد.'}</p><p>الحساب من ${dateLabel(asOf)} وبداية تمويل الهدف؛ لا يشمل راتبًا بعد دخول المناسبة، ولا يسجل تحويلًا.</p><p>${g.cycleSchedule?'الجدول المعتمد: '+g.cycleSchedule.map(s=>s.cycle+': '+fmt(s.amount)).join(' · ')+'. ':''}المخصص المعتمد للدورة المختارة ${fmt(goalMonthlyAllocation(g))}. المطلوب أعلاه اقتراح حسابي، وليس مخصصًا مخصومًا من الفائض.</p><button class="mini" onclick="editItem('goal','${g.id}')">تعديل الموعد والمخصص</button></details></div>`}).join('')}
schemas.goal.push(['excludeDeadlineSalary','التمويل قبل الموعد فقط (استبعاد راتب يوم الموعد)','checkbox'],['scheduleAction','جدول الدفعات الخاص إن وجد','select','الحفاظ على الدفعات المحددة|keep,استبداله بمخصص شهري متكرر|replace']);
const monthlyField=schemas.goal.find(f=>f[0]==='monthlyPlan');if(monthlyField)monthlyField[1]='المخصص الشهري المتكرر (الجدول الخاص مقدّم إن وجد)';
// Confirmed: Ramadan300/300/700/700, investment100/100 then300 monthly.
function applyApprovedSeasonFunding(d){if(d.seasonFundingRevision==='2026-10-04-v1')return d;let r=d.goals.find(g=>g.id==='g-ramadan'),i=d.goals.find(g=>g.id==='g-investment');if(r)Object.assign(r,{target:2000,planStartDate:'2026-10-27',monthlyPlan:300,fundingStatus:'active',cycleSchedule:[{cycle:'2026-10',amount:300},{cycle:'2026-11',amount:300},{cycle:'2026-12',amount:700},{cycle:'2027-01',amount:700}],note:'تقسيمة معتمدة:300 من راتبي أكتوبر ونوفمبر،700 من ديسمبر ويناير. التمويل قبل رمضان، ولا يشمل راتب فبراير داخل رمضان.'});if(i)Object.assign(i,{monthlyPlan:300,planStartDate:'2026-12-27',fundingStatus:'active',cycleSchedule:[{cycle:'2026-12',amount:100},{cycle:'2027-01',amount:100}],recurringAfter:'2027-02-27',note:'خفض معتمد إلى100 في ديسمبر ويناير لتمويل رمضان، ثم300 شهريًا من فبراير. مساهمات فقط؛ لا أرباح أو قيمة سوقية.'});d.seasonFundingRevision='2026-10-04-v1';return d}
if(state.seasonFundingRevision!=='2026-10-04-v1'){let before=JSON.stringify(state);try{let d=applyApprovedSeasonFunding(structuredClone(state));validateState(d);localStorage.setItem('mali-season-funding-before-20261004',before);localStorage.setItem('mali-v7-undo',before);localStorage.setItem('mali-v4',JSON.stringify(d));state=d;lastSaved=JSON.stringify(state)}catch(e){toast('تعذر حفظ تمويل رمضان: '+e.message)}}
const allocationBeforeSeasonFunding=goalMonthlyAllocation;goalMonthlyAllocation=function(g){if(g.recurringAfter&&cycle().start>=g.recurringAfter)return allocationBeforeOctober(g);return allocationBeforeSeasonFunding(g)};
const renderBeforeSeasonDates=render;render=function(){renderBeforeSeasonDates();let html=seasonalFundingRows();$('seasonFunding').innerHTML=html;$('goalsPage').insertAdjacentHTML('afterbegin',`<div class="seasonalOverview"><h3>الرواتب المتاحة للأهداف الموسمية</h3>${html}</div>`)};
render();
