/* Arithmetic forecasts only. No bank sync, payment creation or automatic reallocations. */
function monitorProjection(months=12){let offset=state.offset||0,rows=[],remaining;try{state.offset=Math.max(0,offset);let first=cycle().start;remaining=new Map(state.goals.map(g=>[g.id,Math.max(0,Number(g.target||0)-Number(g.initial||0)-state.transactions.filter(t=>t.type==='vault'&&t.goalId===g.id&&t.date<first).reduce((a,t)=>a+t.amount,0))]));for(let n=0;n<months;n++){let f=surplusFigures(),goals=state.goals.reduce((sum,g)=>{let allocation=goalMonthlyAllocation(g);if(g.target>0){allocation=Math.min(allocation,remaining.get(g.id));remaining.set(g.id,Math.max(0,remaining.get(g.id)-allocation))}return sum+allocation},0);rows.push({date:cycle().start,salary:Number(state.incomePlan?.salary||0),fixed:f.fixedPlan,debt:f.debtPlan,goals,surplus:Math.round((Number(state.incomePlan?.salary||0)-f.fixedPlan-f.debtPlan-goals)*100)/100});state.offset++}}finally{state.offset=offset}return rows}
function monitorGoalGap(g,asOf=currentDate()){let need=goalFundingNeed(g,asOf),offset=state.offset||0,planned=0;try{for(let date of need.dates){let [y,m]=dateParts(date),base=monthDate();state.offset+=((y-base.getFullYear())*12+m-1-base.getMonth());planned+=goalMonthlyAllocation(g)}}finally{state.offset=offset}let gap=Math.max(0,Math.round((need.remaining-planned)*100)/100);return {...need,planned,gap}}
function renderMonitor(){let rows=monitorProjection(),deficits=rows.filter(r=>r.surplus<0),tight=rows.filter(r=>r.surplus>=0&&r.surplus<500),asOf=[currentDate(),cycle().start].sort().at(-1),goals=state.goals.filter(g=>g.target>0&&g.targetDate&&g.fundingStatus!=='paused').map(g=>({g,...monitorGoalGap(g,asOf)})).filter(g=>g.gap>0);let severity=deficits.length?'danger':goals.length||tight.length?'caution':'good';$('planMonitor').className='planMonitor '+severity;let full=`<div class="monitorHeading"><strong>${deficits.length?'عجز متوقع في الخطة':goals.length?'أهداف تحتاج تمويلًا':tight.length?'الفائض ضيق في بعض الأشهر':'الخطة متوازنة حسابيًا'}</strong><button class="mini" onclick="editPlanIncome()">تعديل الدخل</button></div><p>مراقبة ١٢ دورة من ${dateLabel(rows[0].date)} · الراتب فقط</p>${deficits.slice(0,3).map(r=>`<p class="negative">دورة ${dateLabel(r.date)}: عجز ${fmt(-r.surplus)}. الراتب ${fmt(r.salary)} مقابل ثابتة ${fmt(r.fixed)} وأقساط ${fmt(r.debt)} وأهداف ${fmt(r.goals)}.</p>`).join('')}${tight.slice(0,2).map(r=>`<p>دورة ${dateLabel(r.date)}: المتبقي ${fmt(r.surplus)} فقط؛ أي تكلفة إضافية تتجاوز هذا المبلغ تسبب عجزًا.</p>`).join('')}${goals.map(x=>`<p><b>${esc(x.g.name)}</b>: ينقص جدول التمويل ${fmt(x.gap)} قبل ${dateLabel(x.g.targetDate)}. ${x.count?'متاح '+x.count+' رواتب؛ الزيادة اللازمة '+fmt(Math.ceil(x.gap*100/x.count)/100)+' لكل راتب.':'لا رواتب متبقية قبل الموعد.'} <button class="textLink" onclick="editGoalSchedule('${x.g.id}')">تعديل الدفعات</button></p>`).join('')}<details><summary>الفائض المتوقع لكل دورة وحدود الحساب</summary><div class="monitorMonths">${rows.map(r=>`<div><span>${dateLabel(r.date)}</span><b class="${r.surplus<0?'negative':''}">${fmt(r.surplus)}</b></div>`).join('')}</div><p>توقع حسب البيانات المدخلة، وليس رصيد البنك. يُستبعد حساب المواطن من ضمان التغطية. لا تُرحّل فوائض الأشهر تلقائيًا؛ رصيد الطوارئ منفصل. تُحد مخصصات الأهداف بمبلغها المتبقي، والقروض المتكررة تُحسب تحفظيًا حتى تعدّل المتبقي أو جدولها. المصاريف غير المدرجة تحتاج تحديث الخطة.</p></details><div class="monitorActions"><button class="textLink" onclick="show('fixedPage')">المصاريف</button><button class="textLink" onclick="show('debtsPage')">الأقساط</button><button class="textLink" onclick="show('goalsPage')">الأهداف</button></div>`;
$('advisorPage').insertAdjacentHTML('afterbegin',`<section id="monitorDetail" class="planMonitor ${severity}"><h3>تفاصيل مراقبة الخطة</h3>${full}</section>`);
let message=deficits.length?'عجز متوقع '+fmt(-deficits[0].surplus)+' في دورة '+dateLabel(deficits[0].date):goals.length?goals.length+' أهداف تحتاج تمويلًا قبل موعدها':tight.length?'هامش ضيق: '+fmt(tight[0].surplus)+' في '+dateLabel(tight[0].date):'لا عجز مخطط في الدورات القادمة';
$('planMonitor').innerHTML=`<span>${message}</span><button class="textLink" onclick="show('advisorPage')">التفاصيل</button>`;
}
function editPlanIncome(){closeAll();currentType='planIncome';editRef=null;$('formTitle').textContent='تعديل الدخل المخطط';$('formFields').innerHTML=fieldHTML(['salary','الراتب المخطط','number'],state.incomePlan?.salary||0)+fieldHTML(['citizen','حساب المواطن (يظهر منفصلًا)','number'],state.incomePlan?.citizen||0)+'<p>لا يسجل هذا التعديل إيداعًا فعليًا. يتحدث تنبيه العجز عند الحفظ.</p>';$('formOverlay').classList.add('show')}
let scheduleGoalId='',scheduleKind='goal';
function scheduleRow(cycle='',amount=0){return `<div class="scheduleRow"><label>راتب الشهر<input type="month" class="scheduleMonth" value="${esc(cycle)}"></label><label>المخصص<input type="number" class="scheduleAmount" min="0" step="0.01" value="${Number(amount)}"></label><button class="mini" onclick="this.parentElement.remove()">حذف</button></div>`}
function editGoalSchedule(id,kind='goal'){let g=(kind==='debt'?state.debts:state.goals).find(g=>g.id===id);if(!g)return;closeAll();scheduleGoalId=id;scheduleKind=kind;currentType='goalSchedule';editRef=null;$('formTitle').textContent='دفعات '+g.name;$('formFields').innerHTML='<p>الجدول الخاص مقدم على المخصص الشهري. صفر يعني عدم تخصيص ذلك الشهر؛ لا يمثل دفعًا فعليًا.</p><div id="scheduleRows">'+(g.cycleSchedule||[]).map(s=>scheduleRow(s.cycle,s.amount)).join('')+'</div><button class="mini" onclick="addScheduleRow()">إضافة راتب</button>'+(kind==='goal'?fieldHTML(['recurringAfter','استئناف المخصص الشهري بعد الجدول (اختياري)','date'],g.recurringAfter||''):'')+'<p>حذف كل الصفوف يلغي الجدول ويعيد المخصص الشهري الموجود في بيانات الهدف.</p>';$('formOverlay').classList.add('show')}
function addScheduleRow(){$('scheduleRows').insertAdjacentHTML('beforeend',scheduleRow())}
const editBeforeMonitor=editItem;editItem=function(kind,id){editBeforeMonitor(kind,id);if(kind==='goal'||kind==='debt')$('formFields').insertAdjacentHTML('beforeend',`<button class="secondary" onclick="editGoalSchedule('${id}','${kind}')">تعديل جدول الدفعات شهرًا بشهر</button>`)};
const saveBeforeMonitor=$('saveBtn').onclick;$('saveBtn').onclick=()=>{if(currentType==='planIncome'){let salary=Number($('f_salary').value),citizen=Number($('f_citizen').value);if(![$('f_salary').value,$('f_citizen').value].every(v=>v.trim()!=='')||![salary,citizen].every(n=>Number.isFinite(n)&&n>=0))return toast('أدخل مبالغ صحيحة غير سالبة');state.incomePlan={...state.incomePlan,salary,citizen};saveState('حُفظ الدخل وأعيد فحص الخطة');closeAll();return}if(currentType==='goalSchedule'){let schedule=[],seen=new Set();for(let row of document.querySelectorAll('#scheduleRows .scheduleRow')){let month=row.querySelector('.scheduleMonth').value,raw=row.querySelector('.scheduleAmount').value,amount=Number(raw);if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month)||!validDate(month+'-01')||!raw.trim()||!Number.isFinite(amount)||amount<0||seen.has(month))return toast('راجع الأشهر والمبالغ؛ لا تكرر الشهر');seen.add(month);schedule.push({cycle:month,amount:Math.round(amount*100)/100})}let recurring=scheduleKind==='goal'?$('f_recurringAfter').value:'';if(recurring&&!validDate(recurring))return toast('راجع تاريخ استئناف التمويل');if(recurring&&schedule.some(s=>s.cycle>=recurring.slice(0,7)))return toast('استئناف المخصص يجب أن يكون في شهر بعد آخر دفعة خاصة');let g=(scheduleKind==='debt'?state.debts:state.goals).find(g=>g.id===scheduleGoalId);if(!g)return;if(schedule.length)g.cycleSchedule=schedule.sort((a,b)=>a.cycle.localeCompare(b.cycle));else delete g.cycleSchedule;if(recurring)g.recurringAfter=recurring;else delete g.recurringAfter;saveState('حُفظ الجدول وأعيد فحص المواعيد والعجز');closeAll();return}return saveBeforeMonitor()};
const renderBeforeMonitor=render;render=function(){renderBeforeMonitor();renderMonitor()};
render();
const validateBeforeMonitor=validateState;validateState=function(d){validateBeforeMonitor(d);if(d.incomePlan)for(let key of ['salary','citizen'])if(d.incomePlan[key]!=null&&(!Number.isFinite(d.incomePlan[key])||d.incomePlan[key]<0))throw Error('دخل مخطط غير صالح');for(let x of [...d.goals,...d.debts]){for(let key of ['monthlyPlan'])if(x[key]!=null&&(!Number.isFinite(x[key])||x[key]<0))throw Error('مخصص غير صالح');for(let key of ['planStartDate','recurringAfter'])if(x[key]&&!validDate(x[key]))throw Error('موعد تمويل غير صالح');if(x.cycleSchedule!=null){if(!Array.isArray(x.cycleSchedule))throw Error('جدول دفعات غير صالح');let seen=new Set();for(let s of x.cycleSchedule){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(s.cycle)||!validDate(s.cycle+'-01')||seen.has(s.cycle)||!Number.isFinite(s.amount)||s.amount<0)throw Error('دفعة غير صالحة أو شهر مكرر');seen.add(s.cycle)}}}return d};
