const fs=require('fs'),vm=require('vm'),assert=require('assert');let source=fs.readFileSync(__dirname+'/dashboard-verify.cjs','utf8');
// Use the finance harness independently to avoid nesting eval variable declarations.
let harness=fs.readFileSync(__dirname+'/verify.cjs','utf8').split('// Bank grouping changes')[0];
harness+=`
let seasonalHistory=run('JSON.stringify(state.transactions)');vm.runInContext(fs.readFileSync(__dirname+'/../banks.js','utf8'),ctx);vm.runInContext(fs.readFileSync(__dirname+'/../dashboard.js','utf8'),ctx);vm.runInContext(fs.readFileSync(__dirname+'/../goal-timing.js','utf8'),ctx);
assert.equal(run('JSON.stringify(state.transactions)'),seasonalHistory);
assert.equal(run("goalSalaryDates(state.goals.find(g=>g.id==='g-ramadan'),'2026-10-04').length"),4);
assert.equal(run("goalSalaryDates(state.goals.find(g=>g.id==='g-ramadan'),'2026-10-04').at(-1)"),'2027-01-27');
assert.equal(run("goalSalaryDates(state.goals.find(g=>g.id==='g-adha'),'2026-10-04').length"),7);
assert.equal(run("goalSalaryDates(state.goals.find(g=>g.id==='g-ramadan'),'2027-02-08').length"),0);
assert.equal(run("goalSalaryDates({targetDate:'2027-01-27',planStartDate:'2027-01-27',excludeDeadlineSalary:true},'2027-01-27').length"),0);
assert.equal(run("goalSalaryDates({targetDate:'2027-01-27',planStartDate:'2027-01-27'},'2027-01-27').length"),1);
let seasonalForecast=run('forecastMonths()');assert.deepEqual(JSON.parse(JSON.stringify(seasonalForecast.map(x=>Math.round(x.salaryOnly*100)/100))),[197.76,356.76,929.76,1624.76,2407.76,2407.76,2407.76]);
run('state.offset=3');assert.equal(run("goalMonthlyAllocation(state.goals.find(g=>g.id==='g-investment'))"),100);run('state.offset=5');assert.equal(run("goalMonthlyAllocation(state.goals.find(g=>g.id==='g-investment'))"),300);
let fundingState=run('JSON.stringify(state)');run('applySeasonDates(state);applyApprovedSeasonFunding(state)');assert.equal(run('JSON.stringify(state)'),fundingState);
run("currentType='goal';editRef={kind:'goal',id:'g-majlis'};readForm=()=>({...state.goals.find(g=>g.id==='g-majlis'),targetDate:'2027-01-01',scheduleAction:'keep'})");let councilSchedule=run("JSON.stringify(state.goals.find(g=>g.id==='g-majlis').cycleSchedule)");el('saveBtn').onclick();assert.equal(run("JSON.stringify(state.goals.find(g=>g.id==='g-majlis').cycleSchedule)"),councilSchedule);
vm.runInContext(fs.readFileSync(__dirname+'/../monitor.js','utf8'),ctx);run('state.offset=1');let monitorBefore=run('JSON.stringify(state)');let monitorRows=run('monitorProjection()');assert.equal(monitorRows.length,12);assert.equal(monitorRows[0].surplus,197.76);assert.equal(run('JSON.stringify(state)'),monitorBefore);assert.equal(run("monitorGoalGap(state.goals.find(g=>g.id==='g-ramadan'),'2026-10-04').gap"),0);assert.equal(run("monitorGoalGap(state.goals.find(g=>g.id==='g-adha'),'2026-10-04').gap"),1500);run('state.incomePlan.salary=8000');assert(run('monitorProjection().some(r=>r.surplus<0)'));run('renderMonitor()');assert(el('planMonitor').innerHTML.includes('عجز متوقع'));run('state.incomePlan.salary=13780');run("state.goals.find(g=>g.id==='g-ramadan').cycleSchedule[0].amount=250");assert.equal(run("monitorGoalGap(state.goals.find(g=>g.id==='g-ramadan'),'2026-10-04').gap"),50);run("state.goals.find(g=>g.id==='g-ramadan').cycleSchedule[0].amount=300");assert.equal(run("monitorGoalGap(state.goals.find(g=>g.id==='g-ramadan'),'2027-02-08').gap"),2000);assert.equal(run('JSON.stringify(state.transactions)'),seasonalHistory);console.log('PASS:12-cycle monitor restores state, salary-only deficits, goal gaps including overdue deadline, no automatic transactions.');
vm.runInContext(fs.readFileSync(__dirname+'/../compact.js','utf8'),ctx);let compactBefore=run('JSON.stringify(state)');let six=run('sixMonthScenario()');assert.equal(six.rows[0].date,'2026-10-27');assert.equal(six.rows.at(-1).date,'2027-03-27');assert.equal(Math.round(six.surplus*100)/100,7924.56);assert.equal(six.retained,7132.08);assert.equal(Math.round(six.debt*100)/100,21355.44);assert.equal(six.goals.find(g=>g.id==='g-emergency').added,5400);assert.equal(six.goals.find(g=>g.id==='g-majlis').added,3150);assert.equal(six.goals.find(g=>g.id==='g-ramadan').added,1800);assert.equal(six.goals.find(g=>g.id==='g-investment').added,720);assert.equal(run('JSON.stringify(state)'),compactBefore);run("currentType='fixed'");assert.equal(run("validate({name:'house',amount:0,dueDay:27,startDate:'2026-10-27'})"),'');assert(!el('planMonitor').innerHTML.includes('monitorMonths'));assert.equal(el('dashboardExecutionSection').hidden,true);console.log('PASS: compact homepage, zero planned budgets, six-payday90%scenario and state preserved.');
console.log('PASS: Ramadan4 paydays excludes February, Adha7, deadline boundaries, approved seasonal contributions and surplus, investment resumes, no automatic payments, idempotence and date edits preserve council schedule.');
`;
vm.runInThisContext('(function(require,__dirname){'+harness+'\n})')(require,__dirname);
