const fs=require('fs'),vm=require('vm'),assert=require('assert');
const nodes=new Map(),storage=new Map();
function el(id){if(!nodes.has(id))nodes.set(id,{id,innerHTML:'',textContent:'',style:{},classList:{add(){},remove(){},toggle(){}},setAttribute(){},addEventListener(){},appendChild(){},remove(){},insertAdjacentHTML(){},insertBefore(){},querySelector(){return el(id+'child')},querySelectorAll(){return []},value:'',checked:false});return nodes.get(id)}
const ctx={console,Intl,Date,Math,Number,String,JSON,Set,Error,structuredClone,document:{getElementById:el,createElement:()=>el(Math.random()),querySelectorAll:()=>[],addEventListener(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},navigator:{},scrollTo(){},setTimeout(){},confirm:()=>true,prompt:()=>null,window:{print(){}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/../app.js','utf8'),ctx);function run(s){return vm.runInContext(s,ctx)}
assert.equal(run('cycle().start'),'2026-09-27');assert.equal(run('cycle().end'),'2026-10-27');assert.equal(run("appliesDate('2026-10-26')"),true);assert.equal(run("appliesDate('2026-10-27')"),false);assert.equal(run("fixedActual('f-wife')"),500);assert.equal(run("fixedActual('f-mobile')"),650);assert.equal(run('totals().income'),13780);assert(Math.abs(run('totals().expenses')-7676.86)<.001);assert.equal(run("validDate('2026-02-30')"),false);assert.equal(run("validDate('2028-02-29')"),true);
run('state.offset=-1');assert.equal(run('cycle().start'),'2026-08-27');run('state.offset=0');
let original=run('JSON.stringify(REAL_SEED)');let seed=fs.readFileSync(__dirname+'/seed-original.json','utf8');assert.deepEqual(JSON.parse(original.replace('8.3.0','5.0.0')),JSON.parse(seed));
run("currentType='fixed'");assert(run("validate({name:'x',amount:100,dueDay:32,startDate:'2026-09-27'})"));
assert.throws(()=>run("validateState({...state,transactions:[{id:\"bad'\",name:'x',type:'income',amount:1}]})"));
assert.equal(run("state.fixed.find(x=>x.id==='f-wife').amount"),400);assert.equal(run("state.fixed.find(x=>x.id==='f-wife-mobile').amount"),200);assert.equal(run("state.fixed.find(x=>x.id==='f-personal').amount"),1800);assert.equal(run("state.fixed.find(x=>x.id==='f-charity').amount"),200);assert.equal(run("state.fixed.find(x=>x.id==='f-uni').estimatedInstallments"),7);let fixedCount=run('state.fixed.length');run('applyPlanRevision(state)');assert.equal(run('state.fixed.length'),fixedCount);
const before=run('state.transactions.length');run("deleteItem('goal','g-emergency')");assert.equal(run('state.transactions.length'),before);assert(run("state.goals.some(x=>x.id==='g-emergency')"));
run("payFixed('f-house')");el('f_amount').value='250';el('f_date').value='2026-10-04';el('saveBtn').onclick();assert.equal(run("fixedActual('f-house')"),250);
run("payFixed('f-house')");el('f_amount').value='0';el('f_date').value='2026-10-04';el('saveBtn').onclick();assert.equal(run("fixedActual('f-house')"),0);assert.equal(run("state.transactions.filter(x=>x.fixedId==='f-house').length"),1);
run("payFixed('f-house')");el('f_amount').value='99';el('f_date').value='2026-10-27';el('saveBtn').onclick();assert.equal(run("fixedActual('f-house')"),0);run('closeAll();undoChange()');assert.equal(run("fixedActual('f-house')"),250);

const rem=run("state.debts.find(x=>x.id==='dt193').remaining"),count=run("state.debts.find(x=>x.id==='dt193').installments");let answers=['100','2026-10-04'];ctx.prompt=()=>answers.shift();run("payDebt('dt193')");assert.equal(run("state.debts.find(x=>x.id==='dt193').remaining"),rem-100);assert.equal(run("state.debts.find(x=>x.id==='dt193').installments"),count);
run("show('reportsPage');render();show('calendarPage');render()");
console.log('PASS: seed preserved, render/navigation, salary cycle boundaries, actual matching, totals, leap dates, input validation, linked-goal protection, fixed payments, undo and partial debt payments.');

run("state.transactions.push({id:'test-personal',name:'بنزين',type:'expense',budgetId:'f-personal',amount:100,date:'2026-10-04'});saveState()");run("payFixed('f-personal')");el('f_amount').value='150';el('f_date').value='2026-10-04';el('saveBtn').onclick();assert.equal(run("fixedActual('f-personal')"),150);assert(run("state.transactions.some(x=>x.id==='test-personal')"));console.log('PASS: planned amounts, estimated university, idempotent migration and preservation of linked expense history.');

assert.equal(run("state.goals.find(x=>x.id==='g-majlis').planStartDate"),'2026-10-27');assert.equal(run("goalMonthlyAllocation(state.goals.find(x=>x.id==='g-majlis'))"),0);assert.equal(run("goalMonthlyAllocation(state.goals.find(x=>x.id==='g-istanbul'))"),0);run('state.offset=1');assert.equal(run("goalMonthlyAllocation(state.goals.find(x=>x.id==='g-majlis'))"),1500);assert.equal(run("goalProjectedEnd(state.goals.find(x=>x.id==='g-majlis'))"),'27/12/2026 (تقديري)');let figures=run('surplusFigures()');assert.equal(figures.planned,figures.plannedIncome-figures.fixedPlan-figures.debtPlan-figures.goalPlan);run('state.offset=0');assert.equal(run('surplusFigures().actual'),run('totals().available'));console.log('PASS: goal start date, postponed travel, projected completion and surplus formulas.');

run("state.offset=1;state.transactions.push({id:'test-council-paid',type:'vault',goalId:'g-majlis',name:'دفعة مجلس',amount:1500,date:'2026-10-27'})");assert.equal(run("goalProjectedEnd(state.goals.find(x=>x.id==='g-majlis'))"),'27/12/2026 (تقديري)');run("state.transactions=state.transactions.filter(x=>x.id!=='test-council-paid');state.offset=0");console.log('PASS: completion date accounts for the current contribution.');

assert.equal(run("state.fixed.find(x=>x.id==='f-uni').amount"),725);assert.equal(run("state.fixed.find(x=>x.id==='f-electric').amount"),500);assert.equal(run("state.goals.find(x=>x.id==='g-adha').target"),1500);assert.equal(run("state.debts.some(x=>x.id==='dac')"),false);assert.equal(run("state.fixed.find(x=>x.id==='f-entertainment').amount"),500);run('state.offset=1');assert.equal(run("cycleDebtAmount(state.debts.find(x=>x.id==='dtamara73'))"),73);assert.equal(run("cycleDebtAmount(state.debts.find(x=>x.id==='dtamara152'))"),159);run('state.offset=3');assert.equal(run("cycleDebtAmount(state.debts.find(x=>x.id==='dt193'))"),195);assert.equal(run("cycleDebtAmount(state.debts.find(x=>x.id==='dtamara73'))"),0);run('state.offset=5');assert.equal(run("cycleDebtAmount(state.debts.find(x=>x.id==='dt193'))"),0);run('state.offset=0');console.log('PASS: confirmed budgets, removed AC, seasonal target and scheduled Tabby/Tamara amounts.');

// Isolated forecast with original transactions: earlier tests deliberately inserted payments.
run("state=applyOctoberStart(applyGoalTiming(applyPlanRevision(structuredClone(REAL_SEED))));state.confirmedRevision='';state=applyConfirmedCorrections(state);state.octoberStartRevision='';state=applyOctoberStart(state);state.offset=0");let rows=run('forecastMonths()');assert.equal(rows.length,7);assert.deepEqual(JSON.parse(JSON.stringify(rows.map(x=>Math.round(x.salaryOnly*100)/100))),[497.76,656.76,1729.76,2424.76,2707.76,2707.76,2707.76]);assert.deepEqual(JSON.parse(JSON.stringify(rows.map(x=>x.temporary))),[710,551,478,283,0,0,0]);console.log('PASS: October-first installment schedule and seven monthly surplus totals.');

const txBeforeInvestment=run('JSON.stringify(state.transactions)');run('state=applyInvestmentPlan(state)');assert.equal(run('JSON.stringify(state.transactions)'),txBeforeInvestment);let gCount=run('state.goals.length');run('applyInvestmentPlan(state)');assert.equal(run('state.goals.length'),gCount);assert.equal(run("state.goals.find(g=>g.id==='g-investment').monthlyPlan"),300);assert.equal(run("state.goals.find(g=>g.id==='g-investment').planStartDate"),'2026-12-27');let revised=run('forecastMonths()');assert.deepEqual(JSON.parse(JSON.stringify(revised.map(x=>Math.round(x.salaryOnly*100)/100))),[497.76,656.76,1429.76,2124.76,2407.76,2407.76,2407.76]);run('render()');assert(el('approvedAllocations').innerHTML.includes('الاستثمار'));console.log('PASS: approved investment starts in December, no actual payments added, migration does not duplicate, forecast deducts300 and dashboard edit controls render.');

// Bank grouping changes no amounts or transactions; uploaded logos are raster only.
const bankTx=run('JSON.stringify(state.transactions)'),bankSurplus=run('surplusFigures().planned');
run("Object.assign(state.fixed.find(x=>x.id==='f-house'),{bankProvider:'urpay',bankDisplay:'banner'});render()");
assert.equal(run("bankDistribution().find(x=>x.name==='urpay').planned"),1000);
assert(run("bankBadge(state.fixed.find(x=>x.id==='f-house'))").includes('./assets/urpay.webp'));
assert(run("bankBackground(state.fixed.find(x=>x.id==='f-house'))").includes('aria-hidden'));
assert.equal(run('surplusFigures().planned'),bankSurplus);assert.equal(run('JSON.stringify(state.transactions)'),bankTx);
assert.equal(run("safeBankLogo('data:image/svg+xml;base64,AAAA')"),'');assert.equal(run("safeBankLogo('https://bad.example/image.png')"),'');
assert(run("safeBankLogo('data:image/png;base64,AAAA')"));
run("currentType='fixed'");assert(run("validate({name:'x',amount:100,startDate:'2026-10-27',dueDay:27,bankProvider:'custom',bankName:''})"));
console.log('PASS: bank grouping, logo display, unchanged money and history, custom name validation and rejection of unsafe logos.');
