/* Compact summary, complete manual editing and clearly defined six-payday scenario. */
let scenarioAdherence=90;
function sixMonthScenario(rate=scenarioAdherence/100){let saved=state.offset||0,base=monthDate(),start=state.settings.planStartDate||cycle().start,[y,m]=dateParts(start),rows=[],goals=new Map();try{state.offset+=((y-base.getFullYear())*12+m-1-base.getMonth());let first=cycle().start;for(let g of state.goals){let initial=Number(g.initial||0)+state.transactions.filter(t=>t.type==='vault'&&t.goalId===g.id&&t.date<first).reduce((a,t)=>a+t.amount,0);goals.set(g.id,{id:g.id,name:g.name,initial,target:g.target,added:0,planned:0})}for(let n=0;n<6;n++){let f=surplusFigures(),goalPlan=0;for(let g of state.goals){let r=goals.get(g.id),a=goalMonthlyAllocation(g);if(g.target>0)a=Math.min(a,Math.max(0,g.target-r.initial-r.added));goalPlan+=a;r.planned+=a;r.added+=Math.round(a*rate*100)/100}let surplus=Math.round((Number(state.incomePlan?.salary||0)-f.fixedPlan-f.debtPlan-goalPlan)*100)/100;rows.push({date:cycle().start,fixed:f.fixedPlan,debt:f.debtPlan,goals:goalPlan,surplus,retained:Math.round((Math.max(0,surplus)*rate+Math.min(0,surplus))*100)/100});state.offset++}}finally{state.offset=saved}return {rate,rows,goals:[...goals.values()],surplus:rows.reduce((a,r)=>a+r.surplus,0),retained:Math.round(rows.reduce((a,r)=>a+r.retained,0)*100)/100,debt:rows.reduce((a,r)=>a+r.debt,0)}}
function renderScenario(){let s=sixMonthScenario();$('advisorPage').insertAdjacentHTML('afterbegin',`<section class="scenarioReport"><div class="sectionhead"><h3>نتيجة٦ رواتب على خطتك</h3><label>الالتزام <input type="number" min="0" max="100" value="${scenarioAdherence}" onchange="setScenarioAdherence(this.value)">٪</label></div><p>من ${dateLabel(s.rows[0].date)} إلى ${dateLabel(s.rows.at(-1).date)}. الالتزامات كاملة١٠٠٪؛ تحقيق ${scenarioAdherence}٪ من مخصصات الأهداف والاحتفاظ بنفس النسبة من الفائض. الباقي يفترض صرفه خارج الخطة. ليست زيادة١٠٪ على المصاريف، ولا توقعًا مضمونًا.</p><div class="scenarioTable"><div class="scenarioRow scenarioHead"><span>راتب الشهر</span><span>فائض الخطة</span><span>المحتفظ به</span></div>${s.rows.map(r=>`<div class="scenarioRow"><span>${dateLabel(r.date)}</span><b>${fmt(r.surplus)}</b><b>${fmt(r.retained)}</b></div>`).join('')}</div><p>الفائض المتراكم إذا احتفظت به: <b>${fmt(s.retained)}</b>. مجموع دفعات الديون والأقساط: <b>${fmt(s.debt)}</b>؛ ليست كلها تخفيضًا لأصل الدين لأن توزيع الفوائد غير متاح.</p>${s.goals.filter(g=>g.planned>0).map(g=>`<div class="scenarioGoal"><span>${esc(g.name)}</span><b>${fmt(g.added)} مساهمات جديدة</b><small>الموجود قبل البداية ${fmt(g.initial)}${g.target>0?' · نقص تحقيق المستهدف '+fmt(Math.max(0,g.target-g.initial-g.added)):''}</small></div>`).join('')}<p>مخصصات المجلس ورمضان أموال تجهيز وصرف وليست ثروة دائمة. الأضحية غير ممولة في الخطة الحالية. حساب المواطن غير مدرج؛ يضاف فقط عند تحقق نزوله. أرباح الاستثمار صفر في هذا السيناريو. لا يحتسب الصرف من الخزائن، المصاريف غير المدخلة أو تغير الدخل. بعد الحفظ يعاد حساب هذا التقرير من بياناتك.</p></section>`)}
function setScenarioAdherence(value){let n=Number(value);if(!Number.isFinite(n)||n<0||n>100)return toast('النسبة من صفر إلى١٠٠');scenarioAdherence=n;render()}
// Zero budgets are permitted; this does not erase actual transactions.
const validateBeforeCompact=validate;validate=function(o){let err=validateBeforeCompact(o);if(currentType==='fixed'&&o.amount===0&&err==='أدخل مبلغًا أكبر من صفر')return '';return err};
let manualTransactionId='';
const editBeforeCompact=editItem;editItem=function(kind,id){let x=state.transactions.find(t=>t.id===id);if(kind==='transaction'&&x){manualTransactionId=id;currentType='manualTransaction';editRef=null;$('formTitle').textContent='تعديل الحركة الفعلية';$('formFields').innerHTML=fieldHTML(['name','الوصف','text'],x.name)+fieldHTML(['amount','المبلغ (صفر مسموح)','number'],x.amount)+fieldHTML(['date','التاريخ','date'],x.date)+'<p>تبقى الحركة مرتبطة بالبند نفسه. تعديل دفعة الدين يسوّي المتبقي تلقائيًا بفرق المبلغ، دون تغيير جدول الأقساط.</p>';$('formOverlay').classList.add('show');return}return editBeforeCompact(kind,id)};
const saveBeforeCompact=$('saveBtn').onclick;$('saveBtn').onclick=()=>{if(currentType!=='manualTransaction')return saveBeforeCompact();let x=state.transactions.find(t=>t.id===manualTransactionId);if(!x)return;let name=$('f_name').value.trim(),raw=$('f_amount').value.trim(),amount=Number(raw),date=$('f_date').value;if(!name||!raw||!Number.isFinite(amount)||amount<0||!validDate(date))return toast('راجع الاسم والمبلغ والتاريخ');let d=x.type==='debt_payment'&&state.debts.find(d=>d.id===x.debtId);if(d){let remaining=Math.round((d.remaining+x.amount-amount)*100)/100;if(remaining<0)return toast('الدفعة تتجاوز الرصيد المتبقي بعد إلغاء الدفعة السابقة');d.remaining=remaining;d.total=Math.max(d.total||0,remaining)}Object.assign(x,{name,amount:Math.round(amount*100)/100,date});saveState('تم تعديل الحركة وإعادة الحساب');closeAll()};
const deleteBeforeCompact=deleteItem;deleteItem=function(kind,id){let x=state.transactions.find(t=>t.id===id);if(kind==='transaction'&&x?.type==='debt_payment'&&x.debtId){if(!confirm('حذف دفعة الدين وإعادة مبلغها إلى المتبقي؟'))return;let d=state.debts.find(d=>d.id===x.debtId);if(d){d.remaining=Math.round((d.remaining+x.amount)*100)/100;d.total=Math.max(d.total||0,d.remaining)}state.transactions=state.transactions.filter(t=>t.id!==id);saveState('حذفت الدفعة وسُوّي المتبقي');return}return deleteBeforeCompact(kind,id)};
function renderCompactHome(){let d=dashboardFigures(),actual=dashboardMode==='actual',accounts=dashboardMode==='accounts';$('dashboardExecutionSection').hidden=true;document.querySelectorAll('#dashboardPanel > .dashboardGoals,#dashboardPanel > .seasonalOverview').forEach(el=>el.hidden=true);$('dashboardInvestment').hidden=true;$('dashboardLedgerSection').hidden=true;$('dashboardFlowSection').hidden=true;$('dashboardStats').innerHTML=(actual?[['الدخل المسجل',d.income],['المصروف',d.spending],['تحويلات الأهداف',d.transfers]]:[['الراتب',d.salary],['الالتزامات',d.obligations],['الأهداف',d.goals]]).map(([label,n])=>`<div><small>${label}</small><b>${fmt(n)}</b></div>`).join('');$('dashboardStats').hidden=accounts;$('planMonitor').hidden=accounts;$('dashboardPlanNotice').textContent=actual?'حسب الحركات المدخلة؛ لا يمثل رصيد البنك.':'الخطة فقط؛ الصرف والتحويلات الفعلية تسجل يدويًا.';let old=$('homeSummaryLinks');if(old)old.remove();if(!accounts)$('dashboardPanel').insertAdjacentHTML('beforeend',`<div id="homeSummaryLinks" class="homeSummaryLinks"><button class="textLink" onclick="show('advisorPage')">التحليل وخطة٦ أشهر</button><button class="textLink" onclick="show('reportsPage')">السجل والتعديلات</button></div>`)}
const dashboardBeforeCompact=renderDashboard;renderDashboard=function(){dashboardBeforeCompact();renderCompactHome()};
const renderBeforeCompact=render;render=function(){renderBeforeCompact();renderScenario();$('incomePage').insertAdjacentHTML('afterbegin','<button class="secondary" onclick="editPlanIncome()">تعديل الدخل المخطط</button>');$('settingsPage').insertAdjacentHTML('beforeend',fieldHTML(['planStart','بداية الخطة (تقرير٦ أشهر)','date'],state.settings.planStartDate||'')+'<button class="mini" onclick="savePlanStart()">حفظ بداية الخطة</button>');$('reportsPage').insertAdjacentHTML('beforeend',`<section class="manualLedger"><h3>السجل الكامل للدورة · تعديل المبالغ والتواريخ</h3>${totals().tx.map(t=>`<div class="row"><div><strong>${esc(t.name)}</strong><small>${dateLabel(t.date)} · ${fmt(t.amount)}</small></div>${actionButtons('transaction',t.id)}</div>`).join('')||'<p>لا حركات مسجلة.</p>'}</section>`)};
function savePlanStart(){let date=$('f_planStart').value;if(!validDate(date))return toast('اختر تاريخًا صحيحًا');state.settings.planStartDate=date;saveState('تحدثت بداية تقرير الخطة؛ مواعيد البنود تبقى حسب إعداد كل بند')}
render();
